### ISSUE TITLE
使用的时候报 fs 找不到   我安装之后还是不行  这要怎么解决呢 ？？？

### ISSUE THREAD

**Issue by fanyongfeng** [nodeWechat/wechat4u#103]
Module not found: Error: Cannot resolve module 'fs' in /vue-console/node_modules/wechat4u/lib
 @ ./~/wechat4u/lib/core.js 19:10-23

**Comment by issmile** [comment]
请问怎么解决的?

**Comment by fanyongfeng** [comment]
有点忘了   你到node_module wechat4u  下 跑一遍npm i  试试
