### ISSUE TITLE
我想在浏览器中 使用   确报错 fs 找不到   请问 编译的时候要做什么特殊处理么 对于浏览器模式

### ISSUE THREAD

**Issue by fanyongfeng** [nodeWechat/wechat4u#104]
ERROR in ./~/wechat4u/lib/core.js
Module not found: Error: Cannot resolve module 'fs' in /Users/fanyongfeng/study/vue-console/node_modules/wechat4u/lib
 @ ./~/wechat4u/lib/core.js 19:10-23

**Comment by udbmnm** [comment]
不用作特殊处理，默认就处理过了

**Comment by spacelan** [comment]
用webpack打包么？
https://webpack.github.io/docs/configuration.html#node

**Comment by fanyongfeng** [comment]
在本地的webpack  加了  node : {fs: 'empty'} 可以了
