### ISSUE TITLE
pass_ticket 在浏览器端获取不到  这需要怎么解决呢  谢谢 🙏

### ISSUE THREAD

**Issue by fanyongfeng** [nodeWechat/wechat4u#105]

**Comment by fanyongfeng** [comment]
好像是少了参数 version

**Comment by fanyongfeng** [comment]
加了参数  直接打开 那个get请求时可以获取到的   但是在 页面的 newtwork  里面 没有

**Comment by spacelan** [comment]
这个，你现在这个运行时能够跨域么？

**Comment by fanyongfeng** [comment]
我  把  get 地址 直接copy 出来 在  浏览器里面 打开  是可以获取的到    但是  发请求 是不可以的   这个要 跨域解决么 ？

**Comment by stonexer** [comment]
对，请求会受浏览器跨域限制的。本地做着玩可以想办法跨域，但就不能做成网站使用了，跨域问题是没法绕过的。

**Comment by udbmnm** [comment]
你直接在自己域下玩么。。。 :joy:

**Comment by fanyongfeng** [comment]
那就只能让 后端去获取这个 字段   然后 传回来  ？

**Comment by udbmnm** [comment]
@fanyongfeng 你真想本地直接玩？

**Comment by fanyongfeng** [comment]
没有啊   我只是不懂怎么弄

**Comment by udbmnm** [comment]
@fanyongfeng 默认项目就是直接可以跑起来的

**Comment by fanyongfeng** [comment]
@udbmnm 那我本地开发的时候该怎么弄呢？？

**Comment by fanyongfeng** [comment]
@udbmnm 留个QQ 交流一下 ？

**Comment by udbmnm** [comment]
@fanyongfeng 已邮件你

**Comment by spacelan** [comment]
如果做成浏览器扩展，比如chrome extension，就可以取消跨域的限制

**Comment by udbmnm** [comment]
chrome extension 确实很爽，不过唯一缺点是不能主动上传媒体文件，想了各种办法不行 @spacelan  是否可以把cookie和请求参数给后端上传媒体文件id返回到前端，不知道微信会不会检测ip不让上传，我还没测试这种方法

**Comment by spacelan** [comment]
@udbmnm 之前是能够上传的，现在不清楚怎么回事，好久没管chrome extension了

我有空了去看看

另外你能定位到上传出错的原因么？

**Comment by udbmnm** [comment]
@spacelan 用程序主动选择文件上传在浏览器不行，扩展也没这权限。我手动用input file 上传发现请求没发就上传失败
