### ISSUE TITLE
不想打日志，node在windows上后台运行，这么设置，谢谢

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#111]
不想打日志，node在windows上后台运行，这么设置，谢谢

**Comment by spacelan** [comment]
不想输出日志就不要加`DEBUG`环境变量

**Comment by jiaojunjiaojun** [comment]
@spacelan 是每个页面把debug去掉吗，还是？？

**Comment by spacelan** [comment]
https://github.com/nodeWechat/wechat4u/blob/master/package.json#L14

把`DEBUG=wechat,core`去掉就没日志了

**Comment by jiaojunjiaojun** [comment]
谢谢，还有这样应该能提高性能吧

**Comment by stonexer** [comment]
@jiaojunjiaojun 😂  也许能提高那么一丢丢吧 ...

**Comment by jiaojunjiaojun** [comment]
@stonexer  你好，我这么能后台启动，就是关闭控制台，我的程序也在运行

**Comment by stonexer** [comment]
没用过 windows 的 bash，找找类似 nohup 的东西？
