### ISSUE TITLE
不能监听 登出行为么   ？ 还是我写的有什么错误？？

### ISSUE THREAD

**Issue by fanyongfeng** [nodeWechat/wechat4u#112]
botcontext.on('login', () => {
          botcontext.upLoadGroupList(); //群信息
          botcontext.upLoadUserInfo(); //个人信息
          botcontext.on('logout', () => {
            botcontext = null;
            console.log('登出');
          });
          resolve();

**Comment by spacelan** [comment]
没毛病啊，你能打日志看看么

**Comment by fanyongfeng** [comment]
node koa.js  里面 转发的 请求的 日志  打印不出来  有什么办法可以打印出来么
