### ISSUE TITLE
我想把每个bot对象写进redis 里面 ， 如果我重启服务的 话，   我还可以拿着这些信息直接登陆  就不用扫描了，  这种是不是可行的呢 ？

### ISSUE THREAD

**Issue by fanyongfeng** [nodeWechat/wechat4u#115]
我想把每个bot对象写进redis 里面 ， 如果我重启服务的 话，   我还可以拿着这些信息直接登陆  就不用扫描了，  这种是不是可行的呢 ？我试了一下 ， 存进去再拿出来的时候 ，找不到login方法。  搞不懂。

**Comment by spacelan** [comment]
function不能被序列化然后存进redis啊😂

你可以先new一个bot，然后把之前bot的bot.PROP bot.CONF bot.user赋值给新的bot，然后开始同步
