### ISSUE TITLE
好像表情和图片现在不能发送了

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#117]
@spacelan 
![image](https://cloud.githubusercontent.com/assets/22805853/21217045/25f20e30-c2e5-11e6-9385-3622f5b27225.png)

**Comment by spacelan** [comment]
README里那个机器人还是正常的，你能提供更详细的log么

**Comment by spacelan** [comment]
加上DEBUG=core,wechat

**Comment by jiaojunjiaojun** [comment]
@spacelan 好像就我的微信号不能在网页版发图片和表情了，连官网的也不行，应该是有限制的，我今天发的太多了
![image](https://cloud.githubusercontent.com/assets/22805853/21217265/4bd6f81c-c2e6-11e6-9973-d69162045a22.png)

**Comment by spacelan** [comment]
昨天机器人发消息都受限制了

**Comment by udbmnm** [comment]
@jiaojunjiaojun 刚测试官网可以发

**Comment by jiaojunjiaojun** [comment]
@udbmnm 嗯，昨天下午我的发不出去，过了一会儿又能了

**Comment by udbmnm** [comment]
@jiaojunjiaojun 你那是网络问题

**Comment by jiaojunjiaojun** [comment]
@udbmnm ,不是吧，同事的登上去能发，估计是我发的有点多了吧
