### ISSUE TITLE
wechat4u能在浏览器运行跨域链接微信吗？

### ISSUE THREAD

**Issue by xsteamer** [nodeWechat/wechat4u#123]
简介中的兼容浏览器是什么意思啊？我可以仅仅在本地写个html5的网页（没有Node.js服务器）就实现收发微信消息嘛？
不好意思，非专业人事问问题可能不专业

**Comment by udbmnm** [comment]
@xsteamer 可以，比如chrome extension

**Comment by xsteamer** [comment]
@udbmnm 翻了一下代码，很难以想象充斥着class、import、=>等语句和符号的html5文件能在浏览器中正常运行。。。
有个android开发环境叫APICloud，可以根据html5文件生成android APP，其实我是想在android上运行web版微信的，这还能实现吗

**Comment by udbmnm** [comment]
@xsteamer es6的东西可以用webpack打包成es5，不管是APICloud还是Hbuilder都可以实现，因为没有跨域问题

**Comment by spacelan** [comment]
虽然wechat4u用了es6语法，但是经过babel编译后可以兼容主流浏览器

关于跨域，直接在浏览器里打开肯定是不行的，因为浏览器有安全限制。但是你做成hybrid app，在打包的时候申明好app需要访问的域，就能够正常访问了
