### ISSUE TITLE
发送图片接口收到的图片背景色异常

### ISSUE THREAD

**Issue by Flyphy** [nodeWechat/wechat4u#124]

**Comment by Flyphy** [comment]
bot.uploadMedia(fs.createReadStream('./media/test.jpg'))
譬如发送media 文件自带的 test.png，收到的图片非本地图片样子

**Comment by udbmnm** [comment]
@Flyphy  你的图片是透明背景吧

**Comment by Flyphy** [comment]
是透明的，原来源码带的「./media/test.png」这个也是透明背景？发送收到的图片变成黑白的了

**Comment by Flyphy** [comment]
另外发送图片接口是不支持 gif 动图吗

**Comment by udbmnm** [comment]
@Flyphy Gif你在网页版试试

**Comment by udbmnm** [comment]
@Flyphy PNG透明背景黑色是正常的吧

**Comment by spacelan** [comment]
是的，我发现png的透明度会出现问题，不过那是微信服务器转码造成的

**Comment by spacelan** [comment]
gif必须要作为表情发送才行
