### ISSUE TITLE
登出的时候，报错同步失败

### ISSUE THREAD

**Issue by wuhaoworld** [nodeWechat/wechat4u#126]
具体内容如下，跑官方的 run-core.js 也是如此

    错误： Error: 同步失败
        at /Users/wuhao/www/wechat4u/src/core.js:305:13
        at process._tickCallback (internal/process/next_tick.js:103:7)
    错误： Error: 同步失败
        at /Users/wuhao/www/wechat4u/src/core.js:305:13
        at process._tickCallback (internal/process/next_tick.js:103:7)
    错误： Error: 同步失败
        at /Users/wuhao/www/wechat4u/src/core.js:305:13
        at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by udbmnm** [comment]
我刚登陆的时候也有错误： Error: 同步失败，实际上已经是登陆状态了

**Comment by spacelan** [comment]
@wuhaoworld 能否在调试时加上`DEBUG=core`，这样能看到发生错误的request和respond

**Comment by wuhaoworld** [comment]
@spacelan  运行 `DEBUG=core node ./run-core.js`, 登出后得以下结果：

https://gist.github.com/wuhaoworld/816a2e70eb786b2d8cc0b1030b165810

Thanks!

**Comment by spacelan** [comment]
@wuhaoworld 那这样是符合预期的

登出是个异步的过程，向服务器发出登出请求后，需要等待状态同步API返回了`'window.synccheck={retcode:"1101",selector:"0"}'`才表示真正登出了

这里状态同步我做了容错处理，所以你能看到输出了很多次‘同步失败’

**Comment by wuhaoworld** [comment]
@spacelan 当点击登出之后，6 秒左右才真正登出，有没办法做到实时，或者 1~2 秒以内吗

**Comment by spacelan** [comment]
其实你调用logout之后就可以认为已经登出了

**Comment by stonexer** [comment]
@spacelan 大哥，logout 后的实例标记个 zombie 如何，就不再 throw 了。这个错挺让人奇怪的。

**Comment by wuhaoworld** [comment]
@spacelan 
监听 logout 事件，在手机上点击登出，报错 6 秒之后才会触发对应的代码，延迟太严重

**Comment by stonexer** [comment]
@wuhaoworld 这个没有什么好的方法解决，为了容错，不能单次失败就判定登出。
