### ISSUE TITLE
if (selector !== this.CONF.SYNCCHECK_SELECTOR_NORMAL)  这里用全等于有bug

### ISSUE THREAD

**Issue by caomulaodao** [nodeWechat/wechat4u#130]
https://github.com/nodeWechat/wechat4u/blob/master/src/wechat.js#L80
if (selector !== this.CONF.SYNCCHECK_SELECTOR_NORMAL)  这里用全等于有bug，selector是字符串类型的数字，SYNCCHECK_SELECTOR_NORMAL是数字，所以状态返回'0'的时候是没法等于SYNCCHECK_SELECTOR_NORMAL的0，改成 !=。

**Comment by spacelan** [comment]
谢谢

**Comment by spacelan** [comment]
@stonexer 大哥，改回去吧

**Comment by stonexer** [comment]
是时候用 typescript 了 ... 我类型转化下。
