### ISSUE TITLE
这么获取红包的信息

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#136]
这么获取红包的信息，谢谢

**Comment by udbmnm** [comment]
@jiaojunjiaojun 获取不到，只能知道有红包消息，一个功能有没有看网页版就知道

**Comment by jiaojunjiaojun** [comment]
@udbmnm 对，我就想要  有红包消息提醒的那种

**Comment by udbmnm** [comment]
@jiaojunjiaojun 这个是可以获取到的

**Comment by jiaojunjiaojun** [comment]
@udbmnm 我打日志的时候，发红包或取不到

**Comment by udbmnm** [comment]
@jiaojunjiaojun 几秒钟前我测试会收到“收到红包，请在手机上查看”

**Comment by spacelan** [comment]
示例在run-core.js里面

**Comment by jiaojunjiaojun** [comment]
@spacelan 谢谢，看到了
