### ISSUE TITLE
微信群中发送图片失败

### ISSUE THREAD

**Issue by eddiework** [nodeWechat/wechat4u#137]
Error: 发送图片失败
    at D:\bot\node_modules\wechat4u\lib\core.js:713:15
    at process._tickCallback (internal/process/next_tick.js:103:7)

1分钟发送1次图片，过一些时间后图片发送失败，然后后面的图片全部发送失败。debug了core里面的error

 data:
  { BaseResponse: { Ret: 1205, ErrMsg: '' },
    MsgID: '',
    LocalID: '' } }

**Comment by eddiework** [comment]
在描述下场景，队列中n张不同的图片，定时1分钟往群里发一张，发到一定时间后，后续发送图片会失败，这个时间不一定。重新登陆接着发，same。如果换个微信号发就又能发。 会不会腾讯那边对发送的数量有控制？

**Comment by spacelan** [comment]
就是超过微信的限制了，目前无解诶

**Comment by udbmnm** [comment]
@eddiework 我定时发一天也没事啊
