### ISSUE TITLE
syncPolling 有时候跑跑循环就停了

### ISSUE THREAD

**Issue by zhou-xinghai** [nodeWechat/wechat4u#139]
这个函数有时候不声不响就停掉了，core中的debug日志也没看出什么异常信息，偶尔复现。大家知道可能什么原因么。从日志看core 文件 sync 函数进入后没有退出导致问题。没有任何异常显示。

**Comment by spacelan** [comment]
是的，我也发现了，现在还没有确定问题出在哪，感觉好像是网络的原因

最简单的解决办法就是再设置一个定时器，发现一段时间没有syncPolling后就认为已经下线

**Comment by spacelan** [comment]
#142

**Comment by zhou-xinghai** [comment]
异常停掉直接重启syncPolling好像就可以，无需重新登录，也就是之前的key应该还是生效的。
