### ISSUE TITLE
群中发送的图片信息，语音信息等，这么获取是群中的那个人发出的

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#140]
@spacelan @stonexer 群中发送的图片信息，语音信息等，这么获取是群中的那个人发出的

**Comment by spacelan** [comment]
如果是图片语音消息，`Msg.Content`是一个xml，里面会带有发送者的UserName

**Comment by jiaojunjiaojun** [comment]
谢谢

**Comment by jiaojunjiaojun** [comment]
@spacelan 群里边的username和通讯录这个人的username不是一样的吧

**Comment by spacelan** [comment]
群成员可以通过群Contact的MemberList获得，如果一个群成员是你的好友，那也会出现在你自己的Contacts里面，UserName是一致的

**Comment by jiaojunjiaojun** [comment]
@spacelan 
![image](https://cloud.githubusercontent.com/assets/22805853/22179654/6c1312ce-e095-11e6-867b-a55f6a268022.png)
fromusername和通讯录中的不一样

**Comment by jiaojunjiaojun** [comment]
@spacelan  找到了，谢谢
