### ISSUE TITLE
无法下载视频/小视频？

### ISSUE THREAD

**Issue by windchase** [nodeWechat/wechat4u#145]
运行那个run-core.js，下载视频只是建立一个0字节的.MP4文件，没有任何错误信息。语音则可以完整保存下来。

**Comment by jiaojunjiaojun** [comment]
我也出现这样的问题

**Comment by jiaojunjiaojun** [comment]
@spacelan @stonexer  你好，这是因为微信升级引起的吗

**Comment by spacelan** [comment]
话说现在wechat4u机器人还是能够正常地下载和上传视频诶

**Comment by jiaojunjiaojun** [comment]
@spacelan 大部分收不到
![image](https://cloud.githubusercontent.com/assets/22805853/22764404/85b21e96-eea5-11e6-9c3f-36590e345058.png)

**Comment by windchase** [comment]
我更新到最新版wechat4u后就没有成功过，windows环境。

**Comment by spacelan** [comment]
checkout到master，试试run-core.js行不行

**Comment by windchase** [comment]
发现一个奇怪的现象：下载repository里的test.mp4没问题，自己手机拍的视频或者别人发过来的视频就不行。

**Comment by udbmnm** [comment]
@windchase 你自己在网上找一个小电影.mp4试试看

**Comment by windchase** [comment]
刚试过，还是不行。

**Comment by windchase** [comment]
这个问题在另一个帖子里confirmed？

**Comment by spacelan** [comment]
还在调查到底是哪种视频，微信直接返回 0 byte

**Comment by spacelan** [comment]
#148

**Comment by jiaojunjiaojun** [comment]
@spacelan 你好我重下载的咱们的代码，还是下载不下小视频，急
![image](https://cloud.githubusercontent.com/assets/22805853/23110101/9760f9de-f759-11e6-9166-38ab86cb5a66.png)

**Comment by spacelan** [comment]
@jiaojunjiaojun 你登录网页版，看看同样的视频能不能够点开播放，如果不能那wechat4u也不能

如果能那麻烦把视频发给我，我尝试解决一下

**Comment by jiaojunjiaojun** [comment]
@spacelan 官方的能，我发到你的微信上，还是那
![image](https://cloud.githubusercontent.com/assets/22805853/23110355/a7bb9166-f75b-11e6-9e09-24afc500af9d.png)

**Comment by jiaojunjiaojun** [comment]
@spacelan 不好意思，打不开，是显示图片，点击不开

**Comment by spacelan** [comment]
恩 点开显示图片就不行了

**Comment by spacelan** [comment]
如果需求只是要转发视频或图片，可以直接用转发接口，不用下载

**Comment by windchase** [comment]
什么转发接口？能详细一点吗？

**Comment by spacelan** [comment]
```js
        bot.sendVideo({
            Content: msg.Content
          }, msg.FromUserName)
          .catch(err => {
            bot.emit('error', err)
          })
        bot.sendPic({
            Content: msg.Content
          }, msg.FromUserName)
          .catch(err => {
            bot.emit('error', err)
          })
```

只要把原来第一个参数改成这样就可以了

还没更新到npm，需要直接clone最新版本

**Comment by windchase** [comment]
@我clone了最新版，试验了一下这种方法。发图片是可以的，视频好像还是不行。是用自己手机微信拍的视频。 @spacelan

**Comment by windchase** [comment]
是否可以考虑对文件也实现这样的转发接口？也就是说，对接收的文件，不下载，直接转发。谢谢。 @spacelan

**Comment by spacelan** [comment]
就是上面提到的接口，直接用就好

**Comment by windchase** [comment]
> bot.sendDoc({ Content: msg.Content }, msg.FromUserName).catch(err => { bot.emit('error', err) })
返回:
错误： Error: 发送文件失败
    at E:/wechat4u/src/core.js:713:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
@spacelan

**Comment by spacelan** [comment]
能加上环境变量`DEBUG=core`看看请求内容么

**Comment by windchase** [comment]
@spacelan  见附件，我是把一个pdf文件分享给wechat的filehelper，然后wechat4u脚本会尝试转发给指定的contact。多谢。
  [error_forwardfile.txt](https://github.com/nodeWechat/wechat4u/files/809760/error_forwardfile.txt)

**Comment by spacelan** [comment]
@windchase 抱歉  代码实现有问题

我准备再写一个专门用于消息转发的方法

**Comment by windchase** [comment]
多谢，期待ing。

**Comment by spacelan** [comment]
最新版本，增加了`forwardMsg方法`，README有说明，run-core.js有例子

**Comment by windchase** [comment]
非常感谢，实测通过。我把这个issue close了。
