### ISSUE TITLE
请问一下在群里如何获得发送者的昵称，而不是备注？

### ISSUE THREAD

**Issue by etnperlong** [nodeWechat/wechat4u#146]
如题。群里的群昵称是从msg.Content里得到的，那如何对应通讯录里的联系人呢？

**Comment by spacelan** [comment]
`msg.OriginalContent `里是发送者的`UserName`，然后你可以在群的`MemberList`中找到这个用户的信息

https://github.com/nodeWechat/wechat4u/blob/master/src/interface/message.js#L41

**Comment by etnperlong** [comment]
非常感谢，我尝试解决一下。
