### ISSUE TITLE
为什么有时收不到文本信息，报这个错误

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#148]
![image](https://cloud.githubusercontent.com/assets/22805853/22764375/496f72c6-eea5-11e6-954d-da282821d1f9.png)

**Comment by spacelan** [comment]
这个错误是wechat4u报的吗？

**Comment by jiaojunjiaojun** [comment]
嗯，群的文本信息有时收不到

**Comment by spacelan** [comment]
还能有具体一点的信息么，这样我也判断不了什么原因

**Comment by jiaojunjiaojun** [comment]
@spacelan  ToUserName:在群里的文本信息不对
![image](https://cloud.githubusercontent.com/assets/22805853/22820689/d74c6f82-efb2-11e6-910c-d4b00f052bf5.png)

**Comment by jiaojunjiaojun** [comment]
@spacelan 群发过来的文本信息ToUserName是个数字
![image](https://cloud.githubusercontent.com/assets/22805853/22821524/780ccd38-efb6-11e6-993c-1ae54fdc4bd1.png)

**Comment by jiaojunjiaojun** [comment]
@spacelan @stonexer 你好在吗，这个问题是？

**Comment by spacelan** [comment]
我搞看不懂这个问题是怎么出现的。。

能不能够单独监听一下 message 事件，看看原始信息是什么样的

**Comment by jiaojunjiaojun** [comment]
![image](https://cloud.githubusercontent.com/assets/22805853/22872742/5f975c7c-f1f6-11e6-9370-2a4eab65b353.png)
![image](https://cloud.githubusercontent.com/assets/22805853/22872755/6dff5a76-f1f6-11e6-8f6d-60a76a3ad80c.png)

**Comment by jiaojunjiaojun** [comment]
@spacelan 我就是在这个文件中打出来的日志
![image](https://cloud.githubusercontent.com/assets/22805853/22872773/95fdc954-f1f6-11e6-8786-a68136adda81.png)

**Comment by spacelan** [comment]
卧槽，这个问题有点严重诶

能不能麻烦你在这里输出一次？

https://github.com/nodeWechat/wechat4u/blob/master/src/wechat.js#L236

**Comment by jiaojunjiaojun** [comment]
就是在群里边，别人发来的文本信息有问题
![image](https://cloud.githubusercontent.com/assets/22805853/22873104/ad075122-f1f8-11e6-899c-be5eab9d08c0.png)

**Comment by jiaojunjiaojun** [comment]
@spacelan

**Comment by stonexer** [comment]
居然只有一位数字？如果是 bug 的话太吓人了。。

**Comment by spacelan** [comment]
@stonexer 大哥觉得那里有问题？

**Comment by stonexer** [comment]
@jiaojunjiaojun 能不能在 @spacelan 发的那行前 `console.log(msg)` 一下看看

https://github.com/nodeWechat/wechat4u/blob/master/src/wechat.js#L236

**Comment by jiaojunjiaojun** [comment]
@spacelan @stonexer  现在好了，为什么
![image](https://cloud.githubusercontent.com/assets/22805853/22873571/cf94e12a-f1fb-11e6-94ef-45f35c1ca9b4.png)

**Comment by stonexer** [comment]
这么神奇。。再观察观察呢，还没发现可能的原因。。

**Comment by jiaojunjiaojun** [comment]
@stonexer 好的，还有个问题，视频为什么大部分下载不下了

**Comment by jiaojunjiaojun** [comment]
@stonexer 这是接收图片报的错
![image](https://cloud.githubusercontent.com/assets/22805853/22873845/7dd8f220-f1fd-11e6-8ef3-a7760b92b0aa.png)

**Comment by spacelan** [comment]
没有返回mediaId，好奇怪

**Comment by jiaojunjiaojun** [comment]
不知道什么情况 @spacelan

**Comment by spacelan** [comment]
不对，是微信做了限制，网页版只能下载通过微信拍摄的视频了

**Comment by jiaojunjiaojun** [comment]
这就是用微信拍的，是不是客户端升级的过
![image](https://cloud.githubusercontent.com/assets/22805853/22875835/b52cc84a-f208-11e6-896a-9ab719fded1e.png)

**Comment by spacelan** [comment]
我自己在网页版上测试就发现只要不是通过微信拍的视频就不能下载播放

不知道你那里又是什么情况

**Comment by jiaojunjiaojun** [comment]
你的客户端是这个版本吗

![image](https://cloud.githubusercontent.com/assets/22805853/22876028/9ee9c9e2-f209-11e6-81d0-3244953dc82c.png)

**Comment by spacelan** [comment]
我ios上是6.5.4

**Comment by jiaojunjiaojun** [comment]
我版本升级以后也不行，我是安卓的

**Comment by spacelan** [comment]
你可以加README上那个机器人，给他发各种视频试试，如果视频能够被网页版下载，机器人就会回复你这个视频

**Comment by jiaojunjiaojun** [comment]
@spacelan 是这个吗
![image](https://cloud.githubusercontent.com/assets/22805853/22877261/a8001abc-f20f-11e6-825e-ce5d60d7b3f5.png)

**Comment by spacelan** [comment]
恩 是这个
