### ISSUE TITLE
怎么通过bot.contacts得到的数据，判断是公众号还是个人？

### ISSUE THREAD

**Issue by dadaa1** [nodeWechat/wechat4u#149]
另外在登陆后获取bot.contacts，数据好像没有群信息！
监听contacts-updated事件，该事件会触发好多次，每次获得信息好像只是一部分~

**Comment by windchase** [comment]
用wechat.Contact.isPublicContact()判断。登陆的时候会获取大部分的contacts。

**Comment by spacelan** [comment]
每一次 contacts-updated 事件传递的数据就是当前这次被更新的 contacts 列表

启动后第一次 contacts-updated 是保存在通讯录里的联系人，群和公众号，之后几次一般是没有保存在通讯录但是还在聊天列表里的群

运行时的 contacts-updated 就是对应的 contact 的信息有更新了，比如联系人修改了名字什么的
