### ISSUE TITLE
上传视频报这个错，是什么错误？谢谢

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#150]
@spacelan  @stonexer  谢谢
![image](https://cloud.githubusercontent.com/assets/22805853/22913301/d78414ce-f2a4-11e6-8da2-2fbad49b3252.png)

**Comment by spacelan** [comment]
502...微信服务器跪了吧

**Comment by jiaojunjiaojun** [comment]
官方的没事呀

**Comment by jiaojunjiaojun** [comment]
@spacelan 你好，我没有更新这次修改，是不是视频传不上去和这个有关系
![image](https://cloud.githubusercontent.com/assets/22805853/23115038/6275e5bc-f77d-11e6-9227-6878f2d927f8.png)

**Comment by spacelan** [comment]
有可能

**Comment by jiaojunjiaojun** [comment]
@spacelan 现在能上传了
