### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by jianzhou520** [nodeWechat/wechat4u#152]
### 登录的流程是
start() [wechat.js] => startInit() [core.js] => startGetContact() [core.js] => emit('login') [core.js]
### 与微信网页版相符，但是有一个严重的问题
在联系人比较多的时候，尤其有很多多人群的时候，startGetContact() [core.js] 会花费相当长的时间，我这边用一个微信号在微信网页版登陆，这个接口pending了2.1min直到死掉。但是手机是显示登录状态的
### 所以
我觉得这里应该把emit('login') [core.js]放到startGetContact() [core.js]之前，然后通过轮训调batchGetContact() [core.js]来获取联系人。
### 但是
自己简单改了下源码，发现登录流程正常，很快又是由于startGetContact() [core.js]导致整个登陆流程失效。

**Comment by stonexer** [comment]
pending 了两分钟么。已经是异常情况了吧。getContact 并不会返回所有联系人的数据，所以应该不会有很大压力的。

**Comment by spacelan** [comment]
getContact 的响应是有点慢， 如果不符合自己的需求可以在自己的应用层单独写一个登录流程，不用改源码

```js
bot.startLogin()
  .then(() => bot.startInit())
  .then(() => {
    bot.emit('login')
    bot.state = bot.CONF.STATE.login
    bot.lastSyncTime = Date.now()
    bot.syncPolling()
    bot.checkPolling()
    // bot.startGetContact() 不需要联系人信息可以不用调用，在收到消息时，如果没有对应联系人信息会单独调用一次batchgetcontact
  }).catch(err => {
    bot.emit('error', err)
    bot.stop()
  })
```

**Comment by jianzhou520** [comment]
我用的一个微信号有3600多联系人，然后我去微信网页版登录，这个接口挂掉后，联系人列表里面的就只有batchGetContact()返回的，所以也用不了。

**Comment by spacelan** [comment]
那这种微信接口问题也很绝望呢，期待微信尽快修复吧

我也是最近才发现这个接口会挂掉，之前只是pending很长时间

**Comment by jianzhou520** [comment]
另外我研究了下，发现微信的web版本貌似是靠getContent()拉取所有联系人列表的（这个接口不通，网页版微信也无法正常使用）。但是PC版本的是多次调用http://short.weixin.qq.com/cgi-bin/micromsg-bin/getcontact，因此联系人再多它也能获取出来，现在看看这个咋回事儿。

**Comment by stonexer** [comment]
@jianzhou520 pc 和 web 的 api 不一样吧。pc 版的应该稳定些。wechat4u 也有 hack 其他平台 api 的打算。

**Comment by jianzhou520** [comment]
api是不一样，而且应该更稳定，我自己尝试了下，未果~_~

**Comment by jianzhou520** [comment]
hack 有什么想法么？发现现在的微信web协议投入到product环境，没法提高生产效率，很容易导致频繁操作然后被微信禁用接口一段时间

**Comment by spacelan** [comment]
@jianzhou520 改成异步获取了，另外也会根据getContact返回的seq来继续获取为获取到的联系人
