### ISSUE TITLE
下载表情符号有时候也会失败

### ISSUE THREAD

**Issue by windchase** [nodeWechat/wechat4u#154]
在run-core.js里，用bot.getMsgImg()获取某些表情符号，保存的文件为空，没有错误信息。网页版微信不显示表情符号，所以没法验证是wechat4u的问题，还是网页版微信的限制。我仔细看了一下，出错的时候msg.Content为空。不知可否解决？

**Comment by spacelan** [comment]
是的，网页版不显示表情商店里的表情，所以也不能够被wechat4u下载

目前只能获取到用户自定义的表情

**Comment by windchase** [comment]
原来如此。只能等你们什么时候实现Windows版微信的接口了:)。
