### ISSUE TITLE
异常处理

### ISSUE THREAD

**Issue by jianzhou520** [nodeWechat/wechat4u#155]
### 现状
目前整个模块里面的异常都是类似于core.js => wechat.js => error[event]，在core.js里面抛异常的时候，代码如下：
```javascript
Promise.resolve().then(() => {
  doSomething();
}).catch((err) => {
  debug(err);
  throw new Error('获取图片或表情失败');
});
```
上面重新覆盖调了异常细节

### 期许
个人还是觉得将异常细节的控制权交给开发者本身比较合理，因为可能会有一些比较复杂的业务内容和异常本身的内容有关

**Comment by spacelan** [comment]
目前是，当设置环境变量`DEBUG=core`时，才会显示 core 里的异常

这样子符合你的需求么？

**Comment by spacelan** [comment]
你的想法是不是这样，

所有异常信息都触发事件但不输出，然后在开发者代码里做处理？

**Comment by jianzhou520** [comment]
输出也是可以的，但是最好也把异常的访问通道对开发者放开

**Comment by spacelan** [comment]
好建议

那有异常时wechat4u用什么方式通知你比较好呢

**Comment by jianzhou520** [comment]
1. error事件的方式；2. catch的方式
主要的是我上面代码提到的，不要把异常信息在最底层就给覆写了

**Comment by stonexer** [comment]
封装一个 error 对象如何。

```
{ code: 404, message: '获取图片或表情失败', error: error }
```

**Comment by jianzhou520** [comment]
封装对象可以，这个code的话就不用了，error里面的BaseResponse有这些信息了

**Comment by spacelan** [comment]
@jianzhou520 v0.7修复了
