### ISSUE TITLE
我打印bot.contacts里面没有内容

### ISSUE THREAD

**Issue by MissU2** [nodeWechat/wechat4u#158]
打印出的都是'@b8c0ba6e12766eddb8d7bc852a311c40': {},
  '@c5f7f55a1636470141bd1bafee8a7f1bda4205e47e731aa537b6ab420779e135': {},
  '@926b3a3f371907b8fb767a04baa147dae1a94e1335c9f3649b6953bb47e9446f': {},
  '@15a76c76086b127c575eec28c572ca36': {},这样 的内容,我想获取联系人的username等等怎么获取到啊?

**Comment by stonexer** [comment]
rawData 在 __proto__ 上，这样便于 update 时的更新，不会修改到自己添加在 contact 上的数据

**Comment by stonexer** [comment]
https://github.com/nodeWechat/wechat4u/blob/master/src/interface/contact.js#L103

**Comment by MissU2** [comment]
我能说我没听懂你的意思吗

**Comment by stonexer** [comment]
这儿的设计可能有点问题啊。不过目前是这个样子的：

```
const contact = {}

contact.__proto__ =  {
  UserName: '123',
  // wechat raw contact data
}

console.log(contact.UserName) // 123
console.log(contact) // {}
```
__proto__ 里的数据是一直在自动更新替换的，比如在手机修改了名字等等

**Comment by MissU2** [comment]
谢谢,方便留个联系方式吗,或者加你qq,我qq2451496034,希望请教你一下下

**Comment by MissU2** [comment]
,有没有可以在run-core.js里面可以获得的用户消息页面的所有联系人啊,包括群啊?

**Comment by spacelan** [comment]
这个设计还是有点问题，要不再改回去？

@stonexer

**Comment by MissU2** [comment]
@spacelan @stonexer来吧,改改改

**Comment by MissU2** [comment]
@stonexer  不过话说我怎么获取用户的消息列表啊

**Comment by stonexer** [comment]
@spacelan 大哥的问题指的是？

**Comment by stonexer** [comment]
@MissU2 消息列表是指历史聊天记录么？目前还没有这样的 API，wechat4u 也没有缓存任何消息，所以可能需要监听 message 消息自己存下来了

**Comment by MissU2** [comment]
@stonexer 我不是这个意思啦,我就是想请求群组列表,就是这个function batchGetContact(contacts)函数,但是我不知道怎么在run-core.js中调用这个函数获取到返回的response.还有能不能建个群让我们吃瓜群众可以互相讨论啊?

**Comment by spacelan** [comment]
@MissU2 v0.7修复了
