### ISSUE TITLE
获取群列表出现新情况

### ISSUE THREAD

**Issue by udbmnm** [nodeWechat/wechat4u#159]
昨天开始获取群列表出现新的情况，以前是只有加入通讯录的才会获取到，昨天发现只要是最近有收到消息（也就是有活跃）的群都会显示出来，不知道大家有遇到没

**Comment by spacelan** [comment]
不是一直都这样么

**Comment by udbmnm** [comment]
@spacelan 昨天才这样的。。。以前只有加入通讯录才行

**Comment by spacelan** [comment]
这个逻辑写了很久了，获取最近联系的群聊，你以前是不是没有注意？

**Comment by windchase** [comment]
我这边的观察也是一直是这样。

**Comment by MissU2** [comment]
怎么获取最近的群聊啊?

**Comment by MissU2** [comment]
@spacelan 可以建个群吗?让我们可以讨论啊?

**Comment by spacelan** [comment]
@MissU2 扫README上的二维码可以拉你入群

**Comment by MissU2** [comment]
@spacelan 早扫描了啊,是个机器人啊

**Comment by MissU2** [comment]
@udbmnm 请问与喜爱你是怎么获得最近群聊的,是bot.contacts吗

**Comment by udbmnm** [comment]
没注意，我看会代码去。。

**Comment by MissU2** [comment]
@udbmnm 可以发给我看下吗?可以加下好友问你问题吗?呜呜呜呜

**Comment by udbmnm** [comment]
@MissU2 你是什么问题

**Comment by jianzhou520** [comment]
去抓瞎网页版的包就知道，登录之后会调两个接口，一个获取历史聊天的联系人列表，一个是获取所有的联系人列表。

**Comment by MissU2** [comment]
@udbmnm 一个是不知道怎么获取所有联系人,包括最近聊天的群的username以及nickname,可能需要我代码截图给你看,qq2451496034
