### ISSUE TITLE
有没有哪位大神写了加好友的接口啊?希望上沟通下啊

### ISSUE THREAD

**Issue by MissU2** [nodeWechat/wechat4u#161]
微信添加群里的好友有没有人写啊

**Comment by spacelan** [comment]
@stonexer 快帮妹子写借口

**Comment by auwaiyung** [comment]
function addChatroomMember(bot, chatroom) {
    if (bot.Contact.isRoomContact(chatroom)) {
        for (let value of chatroom.MemberList) {
            setTimeout(function () {
                addFriend(bot, value.UserName);
            }, 1000);
        }
    }
}

function addFriend(bot, UserName) {
    let params = {
        'pass_ticket': bot.PROP.passTicket,
        'lang': 'zh_CN'
    };

    let data = {
        'BaseRequest': bot.getBaseRequest(),
        'Opcode': 2,
        'VerifyUserListSize': 1,
        'VerifyUserList': [{
            'Value': UserName,
            'VerifyUserTicket': ""
        }],
        'VerifyContent': '我是' + bot.user.NickName,
        'SceneListCount': 1,
        'SceneList': [33],
        'skey': bot.PROP.skey
    };

    return bot.request({
        method: 'POST',
        url: bot.CONF.API_webwxverifyuser,
        params: params,
        data: data
    }).then(res => {
        let data = res.data;
        console.log(data);
    }).catch(err => {
        bot.emit('error', err);
    })
}

**Comment by spacelan** [comment]
@auwaiyung 大神帮忙提个pr？

**Comment by spacelan** [comment]
#177

**Comment by guider** [comment]
加好友 mark

**Comment by guider** [comment]
@guider
