### ISSUE TITLE
updateChatroom怎么获取到MemberList?

### ISSUE THREAD

**Issue by jameskid007** [nodeWechat/wechat4u#162]
有没有一个方法可以通过ChatRoomName去获取群人员列表?

**Comment by spacelan** [comment]
`ChatRoomName`是指的什么？群的`UserName`么？

**Comment by jameskid007** [comment]
恩恩。【 @@8e8bada192e36ef58e446076be2dad1645e4fdf0103dada841d403f6ee5250de】
 我有个需求需要获取群的人员列表.    通过批量获取通讯录（batchGetContact）可以做到吗? 里面的contacts参数的格式是怎么样的?

**Comment by spacelan** [comment]
可以获取到，具体成员信息在群对象的`MemberList`里

**Comment by jameskid007** [comment]
`bot.batchGetContact([{UserName: req.params.uid}])
    .then(function(val){
      var propertys = Object.keys(val);
      debug('属性',propertys.join("\n"));
    })`
求教~,  我就给了一个username参数，获取到的数据是0.  是参数不对吗?  req.params.uid 就是我上面写的那一串@@打头的字符串.

**Comment by spacelan** [comment]
应该是没有问题的

是不是`UserName`不对，每次登录`UserName`都会变化的

**Comment by jameskid007** [comment]
谢谢。
