### ISSUE TITLE
如何换行

### ISSUE THREAD

**Issue by xujialiang** [nodeWechat/wechat4u#163]
抓包看到网页版里是\n 但是，我输入\n，好像没用。 谁知道如何换行？谢谢~~~

**Comment by spacelan** [comment]
在哪换行。。

**Comment by luchongkang** [comment]
怎么在群里输入的内容可以换行的呢

**Comment by spacelan** [comment]
直接加换行符不行了么

在 2019年1月14日，下午4:04，JasonLu <notifications@github.com<mailto:notifications@github.com>> 写道：


怎么在群里输入的内容可以换行的呢

**Comment by luchongkang** [comment]
![1547453548698](https://user-images.githubusercontent.com/3824902/51101787-1e1c5b00-1817-11e9-81d4-b6d43376f696.jpg)
我加了\n这个换行符还是不行

**Comment by spacelan** [comment]
这是你代码问题吧，\n都没被转义

在 2019年1月14日，下午4:12，JasonLu <notifications@github.com<mailto:notifications@github.com>> 写道：


[1547453548698]<https://user-images.githubusercontent.com/3824902/51101787-1e1c5b00-1817-11e9-81d4-b6d43376f696.jpg>
我加了\n这个换行符还是不行

**Comment by luchongkang** [comment]
解决了，使用 %0a 即可。感谢回复🙏
