### ISSUE TITLE
通讯录数据很多时，获取通讯录的数据不完整

### ISSUE THREAD

**Issue by lntmny** [nodeWechat/wechat4u#165]
### wxgetcontact 只调用了一次

> 通讯录数据量少的时候，一次性就可以获取全部数据。
> 通讯录数据量很多时， 取得的数据不完整。

https://github.com/nodeWechat/wechat4u/blob/master/src/core.js#LC184

https://github.com/nodeWechat/wechat4u/blob/master/src/wechat.js#LC151

首次请求时， Seq: 0.
返回的数据中，Seq != 0 时，表示还有数据，递归请求 wxgetcontact ， 设置 Seq 为上次返回的值， 直到返回的 Seq 为 0，才表示通讯录数据获取完成。

这个请求每次返回的数据不是定数， 从几百到一千+， 我测试的最多的一次有 1700+。

**Comment by spacelan** [comment]
感谢！好友数量太少，一直没测试出这个功能！

**Comment by spacelan** [comment]
大神有兴趣优化一下么？

**Comment by stonexer** [comment]
cool ... 
@spacelan 大哥你好友还少啊！

**Comment by reverland** [comment]
wxgetcontact好像本来就只取回一部分？然后用batch啥啥啥的再拉取？

**Comment by spacelan** [comment]
@reverland wxgetcontact应该是把所有联系人，公众号，保存的群取完

**Comment by udbmnm** [comment]
@spacelan  为啥 wxgetcontact 拉取了所有群，居然不包含最近群，一直搞不清楚，还有init已经拉取了最近联系人为何还要batchGetContact再请求一次呢

**Comment by lntmny** [comment]
@spacelan 本人技术不行啊， 长期懒癌发作。整天写 coffeescript ， 写一点点 js 就感觉要虚脱了。ㄟ(川.一ㄟ)

**Comment by spacelan** [comment]
https://github.com/nodeWechat/wechat4u/commit/8404f40b01cd203f2b374aa66db36507d5792ec0

@lntmny 我先写出来了

**Comment by spacelan** [comment]
@udbmnm 
最新版在init的时候没有去获取联系人

之后在同步数据中如果存在StatusNotifyUserName，那么再batchgetcontact一次
