### ISSUE TITLE
v0.70获取联系人有问题

### ISSUE THREAD

**Issue by windchase** [nodeWechat/wechat4u#171]
现在获取的联系人不完整，导致某些群的消息里的member永远是uuid。前面的版本遇到这个问题时，只要在手机里点那个群就可以，现在v.07不行。

**Comment by swuecho** [comment]
更新到7.0 后，新人的发言出现这个问题。

**Comment by spacelan** [comment]
https://github.com/nodeWechat/wechat4u/blob/master/src/wechat.js#L261-L270
可能是这里的原因，获取出错就不错任何操作
尝试后动调用一次`batchGetContact`

**Comment by windchase** [comment]
#197 报告了一个类似的错误。我发现如果群保存在通讯录里，比较容易出现这个问题。

**Comment by spacelan** [comment]
已修复
