### ISSUE TITLE
Suggest: Customize heartbeat message

### ISSUE THREAD

**Issue by littlepiggy03** [nodeWechat/wechat4u#172]
Perhaps add a interface to customize heartbeat message like this?
```javascript
bot.getHeartbeatMessage = function () {
  return (new Date()).toJSON();
};
```
And customize heartbeat interval like this:
```javascript
bot.getHeartbeatInterval = function () {
  return 491520 + Math.random() * 65536;
};
```

Maybe [`src/wechat.js`](https://github.com/nodeWechat/wechat4u/blob/master/src/wechat.js) will be like this:

Code about customize beartbeat message: [(L233)](https://github.com/nodeWechat/wechat4u/blob/master/src/wechat.js#L233) ...
```javascript
      this.notifyMobile()
      .catch(err => {
        debug(err)
        this.emit('error', err)
      })
      this.sendMsg(this.getHeartbeatMessage(), 'filehelper') // Here
      .catch(err => {
        debug(err)
        this.emit('error', err)
      })
```

... And code about customize heartbeat interval [(L239)](https://github.com/nodeWechat/wechat4u/blob/master/src/wechat.js#L239)  ...
```javascript
      clearTimeout(this.checkPollingId)
      this.checkPollingId = setTimeout(() => this.checkPolling(), this.getHeartbeatInterval())
    }
  }
```
Thanks ! XD

**Comment by spacelan** [comment]
Thanks for your good suggestions

Feel free to open a pr
