### ISSUE TITLE
 v0.7.0 restart不能保持登录

### ISSUE THREAD

**Issue by oraoto** [nodeWechat/wechat4u#176]
v0.7.0中同步失败几次后会进行重启（[restart()](https://github.com/nodeWechat/wechat4u/blob/1528c8fa5cc17890fc8a9ccc2972d1abe9326c56/src/wechat.js#L185)），但是重启都没成功。

看了一下代码，重启的逻辑变了，v0.7.0直接调用`init()`，之前会先调用`login()`。

**Comment by spacelan** [comment]
是这样的，你有注意同步失败时报什么错么？

**Comment by oraoto** [comment]
同步失败的时候，都是`AssertionError: '1101' == 0`。

**Comment by oraoto** [comment]
我测试的方法：

1. 扫码登陆
2. 微信APP里点退出“网页微信”

以前的版本在这种情况下是能重新登录的。

**Comment by spacelan** [comment]
啊  没错 以前微信是有这个bug

在登录不久后退出网页微信，或者在另外浏览器上扫码登录，我都能给强制登录回来

不过毕竟是bug，这个版本取消了
