### ISSUE TITLE
请问心跳是不是一定要发一个心跳信息到［文件传输助手］

### ISSUE THREAD

**Issue by hdwong** [nodeWechat/wechat4u#181]

**Comment by spacelan** [comment]
https://github.com/nodeWechat/wechat4u#botsetpollingmessagegettergetter

这里有三个配置心跳的方法

**Comment by hdwong** [comment]
嗯，这个我看了，但是还是得发信息？我看某些基于 Web 版的微信机器人只需要触发一下［文件传输助手］，不需要发信息的，这样会不会友好一点？

**Comment by spacelan** [comment]
_getPollingTarget返回一个不存在联系人吧

**Comment by BiteBit** [comment]
请问设置心跳是可以延长登录时间吗？

**Comment by spacelan** [comment]
@BiteBit 不是一定能延长，不需要你就取消掉心跳
