### ISSUE TITLE
大坑：login和logout不是配套出现的

### ISSUE THREAD

**Issue by baryon** [nodeWechat/wechat4u#183]
今天遇到了大坑，login和logout不是配套出现的，login事件在restart的时候也会发生，而且在发生之前并没有logout事件，所以如果在login事件中做了一些初始化工作，可能会发生执行多次的情况。
数据异常，群发多次等等可怕的事情就会发生了😨😨😨

**Comment by spacelan** [comment]
是哈，只要微信的自己的init等方法成功就触发login，包括在restart的时候

另外在登录过程中，如果发生异常，也会直接触发logout

这些事情之前都没有好好考虑过，你有什么适合你需求的建议？

**Comment by baryon** [comment]
这个坑挺好的，给大家留着吧 😄
