### ISSUE TITLE
发送文本信息失败

### ISSUE THREAD

**Issue by kelvin195eclipse** [nodeWechat/wechat4u#188]
大家好，小弟在Node.js方面是位新手。
目前我在研究如何发文本信息，二维码登录接收信息一切正常，
但在发送文本信息sendMsg()的功能卡住了，
我想要每次收到信息时自动恢复一则简单讯息给发送者，
想问各位大大这要如何解决。

Hello guys, I am newbie on Node.js.
I am currently working on sendMsg() function, other than that, I have no problems with generating barcodes, logging in and receiving messages.
I would like to send a brief message to the sender's account while receiving any messages.
I am currently get stuck in the following problem and wish to get some help.

以下是我导入Modules的程序内容：
Scenario of requiring required modules:
![1](https://cloud.githubusercontent.com/assets/18455592/25340760/4ea4aa76-2939-11e7-8b54-4089ca50bed9.jpg)

以下是我呼叫sendMsg()功能的程序内容：
Scenario of sendMsg() function call:
![2](https://cloud.githubusercontent.com/assets/18455592/25340789/62676364-2939-11e7-8969-2c096a91c121.jpg)

以下是我收到的错误详情：
The error message i received:
![default](https://cloud.githubusercontent.com/assets/18455592/25340622/ebcb7f7e-2938-11e7-8341-abbfda1cf3fc.jpg)

谢谢！
Thank you!

**Comment by spacelan** [comment]
messageSender不应该是displayname

替换成`msg.FromUserName`或者`bot.contacts[msg.FromUserName].UserName`

**Comment by kelvin195eclipse** [comment]
谢谢!多谢大大指导，解决了! =)
