### ISSUE TITLE
如何通过微信号获取用户的UserName

### ISSUE THREAD

**Issue by taojiujiu1986** [nodeWechat/wechat4u#199]
之前写的应用，一直是用微信号作为SendMsg（msg,to）中的to参数的，最近升级了一个weixin4u之后，这个SendMsg就一直发不出去，查下DEMO，知道to参数应该是一个UserName, 那么问题是，我在已知要发送用户的微信号的前提下，如果去调用SendMsg？如果必须要转换成UserName的话，如何转，请帮忙指点，多谢~

**Comment by spacelan** [comment]
原来是可以直接用微信号发消息的，现在好像不可以了

**Comment by spacelan** [comment]
是微信升级了，确认了其他框架也不能用微信号当做UserName了

**Comment by taojiujiu1986** [comment]
那有没有办法转换呢？

**Comment by spacelan** [comment]
你研究一下咯

**Comment by taojiujiu1986** [comment]
@spacelan 额。。。 源码翻了个遍了，没有这块的接口。。。

**Comment by swuecho** [comment]
@taojiujiu1986  check  bot.contacts ?
