### ISSUE TITLE
每次登录大概几分钟，就发不出消息

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#201]
: 1101, ErrMsg: '' }, MsgID: '', LocalID: '' } } +14m
[Error: 发送文本信息失败]
  core { status: 200, statusText: 'OK', headers: { connection: 'close', 'content
-type': 'text/plain', 'content-length': '79' }, config: { transformRequest: { '0
': [Function: transformRequest] }, transformResponse: { '0': [Function: transfor
mResponse] }, headers: { Accept: 'application/json, text/plain, */*', 'user-agen
t': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/48.0.2564.109 Safari/537.36', connection: 'close', cookie: 'p
gv_pvi=7698491392; pgv_si=s8910116864; webwx_data_ticket=gSev1Kg24rIb8Fr/LgNiiXg
V; wxuin=1500245029; wxsid=WRtOXbI06t6mCC9y; wxloadtime=1494315920_expired; mm_l
ang=zh-CN; webwxuvid=6a881c776b3cd282ea6d92ba80f3c205a9e1466194bdc55d2e79ed7e035
61148ae4429bca8edb3cc78ea259401cf4e7f; webwx_auth_ticket=CIsBEKnTkMAEGoABVynl94d
BAO8U74KGT0fvD3n/1GkD9eEy0US2QupY4AMlDCtrdsXc8jzz/FcKJoi0PY8xtE01S5C3vQpmagjWmEY
CvaKKCVwU+XpXUi+lU1fXx9gbfNn/bEdMiKQO3+WEF/3rjZl530cgpKfCio2I8y+UiiVLfhw9BGp5BKC
EQTA; wxpluginkey=1494307801', 'Content-Type': 'application/json;charset=utf-8',
 'Content-Length': 376 }, timeout: 0, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderNa
me: 'X-XSRF-TOKEN', maxContentLength: -1, validateStatus: [Function: validateSta
tus], httpAgent: false, httpsAgent: false, method: 'POST', url: 'https://wx2.qq.
com/cgi-bin/mmwebwx-bin/webwxsendmsg', params: { pass_ticket: 'gZRunKk77btZi4KA8
Gdp8jw%2FedQx85Nz8R7c5Kbd%2BARgzDYavIZ7AtbTWSFDwk94' }, data: '{"BaseRequest":{"
Uin":1500245029,"Sid":"WRtOXbI06t6mCC9y","Skey":"@crypt_614b7b58_9e152c9a36711a5
5c8a31a463b42b155","DeviceID":"e104248922085389"},"Msg":{"Type":1,"Content":"111
","FromUserName":"@f0891fe3b87aa53bab48fd17b31f1ef3c0c098116cf8585b6a313bdd7c9df
64b","ToUserName":"@3190a464a36e7a61004df7062e054276","LocalID":"149431666246100
50","ClientMsgId":"14943166624610050"}}' }, request: ClientRequest { domain: nul
l, _events: { error: [Function: handleRequestError] }, _eventsCount: 1, _maxList
eners: undefined, output: [], outputEncodings: [], outputCallbacks: [], outputSi
ze: 0, writable: true, _last: true, chunkedEncoding: false, shouldKeepAlive: fal
se, useChunkedEncodingByDefault: true, sendDate: false, _removedHeader: { connec
tion: false, 'content-length': false }, _contentLength: 376, _hasBody: true, _tr
ailer: '', finished: true, _headerSent: true, socket: TLSSocket { _tlsOptions: [
Object], _secureEstablished: true, _securePending: false, _newSessionPending: fa
lse, _controlReleased: true, _SNICallback: null, servername: null, npnProtocol:
undefined, authorized: true, authorizationError: null, encrypted: true, _events:
 [Object], _eventsCount: 9, _connecting: false, _hadError: false, _handle: null,
 _parent: null, _host: 'wx2.qq.com', _readableState: [Object], readable: false,
domain: null, _maxListeners: undefined, _writableState: [Object], writable: fals
e, allowHalfOpen: false, destroyed: true, bytesRead: 163, _bytesDispatched: 1313
, _sockname: null, _pendingData: null, _pendingEncoding: '', server: undefined,
_server: null, ssl: null, _requestCert: true, _rejectUnauthorized: true, parser:
 null, _httpMessage: [Circular], read: [Function], _consuming: true, _idleNext:
null, _idlePrev: null, _idleTimeout: -1 }, connection: TLSSocket { _tlsOptions:
[Object], _secureEstablished: true, _securePending: false, _newSessionPending: f
alse, _controlReleased: true, _SNICallback: null, servername: null, npnProtocol:
 undefined, authorized: true, authorizationError: null, encrypted: true, _events
: [Object], _eventsCount: 9, _connecting: false, _hadError: false, _handle: null
, _parent: null, _host: 'wx2.qq.com', _readableState: [Object], readable: false,
 domain: null, _maxListeners: undefined, _writableState: [Object], writable: fal
se, allowHalfOpen: false, destroyed: true, bytesRead: 163, _bytesDispatched: 131
3, _sockname: null, _pendingData: null, _pendingEncoding: '', server: undefined,
 _server: null, ssl: null, _requestCert: true, _rejectUnauthorized: true, parser
: null, _httpMessage: [Circular], read: [Function], _consuming: true, _idleNext:
 null, _idlePrev: null, _idleTimeout: -1 }, _header: 'POST /cgi-bin/mmwebwx-bin/
webwxsendmsg?pass_ticket=gZRunKk77btZi4KA8Gdp8jw%252FedQx85Nz8R7c5Kbd%252BARgzDY
avIZ7AtbTWSFDwk94 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nuser-
agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML
, like Gecko) Chrome/48.0.2564.109 Safari/537.36\r\nconnection: close\r\ncookie:
 pgv_pvi=7698491392; pgv_si=s8910116864; webwx_data_ticket=gSev1Kg24rIb8Fr/LgNii
XgV; wxuin=1500245029; wxsid=WRtOXbI06t6mCC9y; wxloadtime=1494315920_expired; mm
_lang=zh-CN; webwxuvid=6a881c776b3cd282ea6d92ba80f3c205a9e1466194bdc55d2e79ed7e0
3561148ae4429bca8edb3cc78ea259401cf4e7f; webwx_auth_ticket=CIsBEKnTkMAEGoABVynl9
4dBAO8U74KGT0fvD3n/1GkD9eEy0US2QupY4AMlDCtrdsXc8jzz/FcKJoi0PY8xtE01S5C3vQpmagjWm
EYCvaKKCVwU+XpXUi+lU1fXx9gbfNn/bEdMiKQO3+WEF/3rjZl530cgpKfCio2I8y+UiiVLfhw9BGp5B

**Comment by spacelan** [comment]
更新一下版本

**Comment by jiaojunjiaojun** [comment]
好的，我试试
