### ISSUE TITLE
一个诡异的报错

### ISSUE THREAD

**Issue by lmyzzu** [nodeWechat/wechat4u#206]
TypeError: Cannot read property 'length' of undefined
    at ......\node_modules\wechat4u\src\wechat.js:148:37

每次登陆都会出现这个报错

**Comment by baryon** [comment]
在debug on的时候，有刚启动的时候contacts为null，将导致下面这句出错`   debug('getContact count: ', contacts.length)`,触发promise异常。

**Comment by lmyzzu** [comment]
测试了一下，貌似和debug没有关系

**Comment by xujif** [comment]
同碰到，提交了一个PR等待合并 [#227]( https://github.com/nodeWechat/wechat4u/pull/227)

**Comment by spacelan** [comment]
已修复
