### ISSUE TITLE
微信登陆后2小时左右，无故掉线

### ISSUE THREAD

**Issue by marx828** [nodeWechat/wechat4u#208]
登陆微信后大约2个小时会，会出现微信掉线的情况？大神帮忙看看啊~

**Comment by marx828** [comment]
是不是咱们同步的那个post请求没有header导致的呢？？求助

**Comment by marx828** [comment]
@spacelan

**Comment by spacelan** [comment]
掉线之前输出什么错误了？

**Comment by lmyzzu** [comment]
这个问题非常常见
{ Error: timeout of 60000ms exceeded
    at createError (..../node_modules/axios/lib/core/createError.js:15:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (..../node_modules/axios/lib/adapters/http.js:201:16)

**Comment by jiaojunjiaojun** [comment]
![image](https://user-images.githubusercontent.com/22805853/26862936-a4bfaf86-4b81-11e7-8255-03a7dd717c65.png)
在方法syncCheck和sync中输出的错误

**Comment by jiaojunjiaojun** [comment]
@spacelan 求助

**Comment by lmyzzu** [comment]
code: 'ECONNABORTED',
  response: undefined,
  tips: '同步失败' }

**Comment by spacelan** [comment]
恩`socket hang up`就是网络问题或者是微信服务器问题，导致请求挂起了

我设置了 60s 的超时时间，防止程序因此假死
#209
