### ISSUE TITLE
同步联系人发生错误

### ISSUE THREAD

**Issue by wuwb** [nodeWechat/wechat4u#215]
{ AssertionError [ERR_ASSERTION]: '1101' == 0
    at Object.equal (/home/mapp/octopus_marketing/target/node_modules/wechat4u/src/util/global.js:53:14)
    at /home/mapp/octopus_marketing/target/node_modules/wechat4u/src/core.js:327:16
    at run (/home/mapp/octopus_marketing/target/node_modules/core-js/modules/es6.promise.js:87:22)
    at /home/mapp/octopus_marketing/target/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/home/mapp/octopus_marketing/target/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: '1101',
  expected: 0,
  operator: '==',
  response:
   { status: 200,
     statusText: 'OK',
     headers:
      { connection: 'close',
        'access-control-allow-origin': '*',
        'content-type': 'text/javascript',
        'content-length': '46' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 60000,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        Cookie: [Object],
        httpAgent: false,
        httpsAgent: false,
        method: 'GET',
        url: 'https://webpush.wx.qq.com/cgi-bin/mmwebwx-bin/synccheck',
        params: [Object],
        data: undefined },
     data: 'window.synccheck={retcode:"1101",selector:"0"}' },
  tips: '同步失败' }

**Comment by spacelan** [comment]
然后没有登录成功么

**Comment by lmyzzu** [comment]
这个一般是，登陆一段时间后就会发生
