### ISSUE TITLE
当前登录环境异常。为了你的帐号安全，暂时不能登录web微信

### ISSUE THREAD

**Issue by baryon** [nodeWechat/wechat4u#218]
用程序登录不上，
```
<error><ret>1203</ret><message>当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。</message></error>

这可如何是好！
```
用网页出现下面的错误，这是要被封的节奏吗？

![wechat_for_web](https://user-images.githubusercontent.com/421757/27416612-78c1989e-5749-11e7-9d0e-81767e4a9b6c.jpg)

**Comment by stonexer** [comment]
暂时被封了，过段时间会解封的。程序是做了过于频繁的操作么？

**Comment by baryon** [comment]
大概最近用户加的比较多吧。前几天群聊功能也被封过。夹着尾巴做机器人吧
SToneX <notifications@github.com>于2017年6月22日 周四下午12:54写道：

**Comment by spacelan** [comment]
似乎昨天微信搞了点动作，好多机器人都不能用了

**Comment by baryon** [comment]
要把windows／Mac客户端的协议搞搞清楚了。
不过长久看来，一个AI 友好的微信接口，是应该快点推出了。你看LINE， Facebook Messenger， Telegram， Slack等等无一不是走在前头了

**Comment by spacelan** [comment]
微信才不干这种不讨好政府，瓜分自己生态的东西

**Comment by spacelan** [comment]
今天我的微信也出这个提示了，你的恢复了么 @baryon

**Comment by baryon** [comment]
没有，一开始群聊禁言，一对一是可以的。一天后群聊解禁。再过一天，web登陆不上，晚上账号被禁，自己解锁后，仍然是web登录不上。用mac客户端和手机登录是好的。

问了鹅厂的朋友，他也没办法。api的开发计划是有，但是公开的可能性不清楚。


SPACELAN <notifications@github.com>于2017年6月23日 周五下午7:24写道：

**Comment by spacelan** [comment]
哈哈哈，微信前两天的动作看来是要开始断hack机器人这条路子了
