### ISSUE TITLE
微信初始化失败

### ISSUE THREAD

**Issue by qyvlik** [nodeWechat/wechat4u#219]
报错如下：

```
错误： { AssertionError: 1101 == 0
    at Object.equal (/root/software/sosoBot/node_modules/wechat4u/lib/util/global.js:69:24)
    at /root/software/sosoBot/node_modules/wechat4u/lib/core.js:187:24
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'AssertionError',
  actual: 1101,
  expected: 0,
  operator: '==',
  message: '1101 == 0',
  generatedMessage: true,

```

**Comment by qyvlik** [comment]
知道问题了，手机微信上的未读的微信信息太多，到时初始化失败。把手机上未读的微信信息点开就行了。

**Comment by spacelan** [comment]
我去还有这种操作

**Comment by qyvlik** [comment]
@spacelan 部分账户一直出现 `初始化失败` 的话，可以试试到腾讯的微信网页端登陆，如果腾讯的微信网页的也提示 `初始化失败` 话，近期就暂时不操作了。

**Comment by spacelan** [comment]
最近腾讯各种强力打压各种机器人，已经跪倒一大片了

http://mp.weixin.qq.com/s/-mSWgv-qOPnjYqVwZreB2Q

**Comment by gaoryrt** [comment]
同遇见了，网页上也登不上，希望一天后能解封

**Comment by baryon** [comment]
1205 错误基本就是永远封了web登录权限

**Comment by gaoryrt** [comment]
倒是等三个小时（有可能小于三个小时也说不定）又能正常使用了。

**Comment by sunpcm** [comment]
网页版的也登录不上，要等一段时间，大致意思是为了账户安全，现在不允许登录网页版，建议下载mac或者windows的桌面版

**Comment by gaoryrt** [comment]
@sunpcm 2017年那一波把新注册的微信账号网页登录能力全给限制了，实在没辙。要是像 tg 一样能正大光明开发机器人就好了

**Comment by qyvlik** [comment]
@gaoryrt 就是说 2017 年之后注册的微信账户，网页版登陆都会有问题？

**Comment by gaoryrt** [comment]
@qyvlik 微信自然也不会把屏蔽规则公布出来。倒是当时自己摸索出来是半年内的新号都无效了。

**Comment by qyvlik** [comment]
@gaoryrt 有没有谷歌浏览器的 wechat 插件项目，来 hack wechat网页，达到类似此项目的功能？

**Comment by gaoryrt** [comment]
> @gaoryrt 有没有谷歌浏览器的 wechat 插件项目，来 hack wechat网页，达到类似此项目的功能？

https://github.com/nodeWechat/wechat4u#%E7%9B%B8%E5%85%B3%E9%A1%B9%E7%9B%AE
