### ISSUE TITLE
部分微信，通讯录获取不全问题，在手机上给那个好友发消息，就能获取到那个好友

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#223]
@spacelan 这有可能是什么问题呀，谢谢

**Comment by spacelan** [comment]
微信通讯录是分段获取的

https://github.com/nodeWechat/wechat4u#botgetcontactseq

**Comment by jiaojunjiaojun** [comment]
bot.contacts，用这个属性是所有通讯录中的数据吗

**Comment by spacelan** [comment]
设个属性是wechat4u自动帮你获取到的联系人和群信息，是通过主动调用和被动接收消息通知来获取到的

**Comment by jiaojunjiaojun** [comment]
不太明白，用这个属性中的数据做通讯录有问题吗？

**Comment by jiaojunjiaojun** [comment]
@spacelan ,res.Seq返回0就是获取通讯录获取全了吗

![Uploading image.png…]()

**Comment by spacelan** [comment]
@jiaojunjiaojun 没错

**Comment by jiaojunjiaojun** [comment]
![image](https://user-images.githubusercontent.com/22805853/27853328-d54027b6-6194-11e7-9edd-6a4902ab9021.png)
@spacelan

**Comment by jiaojunjiaojun** [comment]
可是返回0了，但是就是不全

**Comment by jiaojunjiaojun** [comment]
![image](https://user-images.githubusercontent.com/22805853/27853461-42ac39fc-6195-11e7-8a90-33b1140097c7.png)
@spacelan  这是代码

**Comment by spacelan** [comment]
是缺群么？

**Comment by jiaojunjiaojun** [comment]
群或好友都有可能缺

**Comment by spacelan** [comment]
我看一下是不是协议变了

**Comment by jiaojunjiaojun** [comment]
![image](https://user-images.githubusercontent.com/22805853/27896356-182f1c64-624c-11e7-89f8-00fd45cf9ae8.png)

**Comment by jiaojunjiaojun** [comment]
@spacelan  你好，这些什么用户

**Comment by jiaojunjiaojun** [comment]
![image](https://user-images.githubusercontent.com/22805853/27982240-d3a9e670-63cf-11e7-9a33-a425c669f459.png)
@spacelan  文件wechat.js中你好为什么要加这段代码

**Comment by spacelan** [comment]
就是为了把保存到通讯录的联系人和群取完

**Comment by jiaojunjiaojun** [comment]
![image](https://user-images.githubusercontent.com/22805853/28235197-b5d03d18-693b-11e7-8798-abd03e945ac4.png)
这儿缺返回值
