### ISSUE TITLE
没有微信群时获取用户列表会出错

### ISSUE THREAD

**Issue by JimmyBryant** [nodeWechat/wechat4u#224]
当微信群列表长度位0的时候。

`debug('getContact count: ', contacts.length);      //contacts为undefined`

查看代码发现wechat.js 的__getContact方法当emptyGroup.length==0的时候没有返回contacts
`      if (Seq == 0) {
        let emptyGroup =
          contacts.filter(contact => contact.UserName.startsWith('@@') && contact.MemberCount == 0)
        if (emptyGroup.length != 0) {
          return this.batchGetContact(emptyGroup)
          .then(_contacts => contacts = contacts.concat(_contacts || []))
        }       // emptyGroup.length==0时没有返回
      } else {
        return contacts
      }`

**Comment by sqzxcv** [comment]
我也看到这个问题,看了源码,应该是在 v0.7.5 "Fix empty group contact"出现这个问题

**Comment by spacelan** [comment]
https://github.com/nodeWechat/wechat4u/pull/227

抱歉，已经更新并发布到npm了
