### ISSUE TITLE
心跳越来越频繁

### ISSUE THREAD

**Issue by z8313568** [nodeWechat/wechat4u#229]
![Uploading WechatIMG64.png…]()

时间长了，心跳发送的频繁，是怎么回事

Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:25 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:27 GMT wechat Sync Check Selector:  2
Tue, 25 Jul 2017 13:03:30 GMT wechat Sync Check Selector:  0
Tue, 25 Jul 2017 13:03:30 GMT wechat Sync Check Selector:  2

**Comment by spacelan** [comment]
这个请求是个长连接，服务器收到请求后直到有新消息或者超时才返回

看日志的样子，27s那里返回的全都是0，说明没有新消息，不知道为什么服务器返回了

也有可能是我们代码的原因，重复发了请求什么的

**Comment by z8313568** [comment]
图片我上传不了，在filehelper开始发送来的心跳都是5分钟一次，后来就变成10几秒一次了，我用的wechatBot，修改了下加的wechat4u v0.75。

**Comment by spacelan** [comment]
那可能是我们代码的问题

**Comment by spacelan** [comment]
是不是你代码里多次触发了一些同步方法？
