### ISSUE TITLE
能支持语音的发送吗

### ISSUE THREAD

**Issue by vimer** [nodeWechat/wechat4u#23]
我想实现多个群的互转，尤其是语音

**Comment by stonexer** [comment]
目前 web 微信还没有语音的功能，也没发现相关的 API，得等等它的更新信息了。多个群里消息的互转应该还是可以实现的吧。

**Comment by vimer** [comment]
群互转基于你这个 是非常简单的，主要是语音的互转，看来其他支持这个 不是通过web协议来的

**Comment by spacelan** [comment]
大哥，，不是可以收语音么 。。
`webwxgetvoice`

**Comment by vimer** [comment]
@spacelan 收和发的协议是不一样的

**Comment by spacelan** [comment]
@vimer 不知道sendMsg带上mediaId和msgType行不行，像图片那样

**Comment by vimer** [comment]
type我改成了语音的type是不行的 mediaId没试过

**Comment by spacelan** [comment]
当成文件发送吧，目前只能这样了
