### ISSUE TITLE
是否有办法获取每个用户固定不变的ID？

### ISSUE THREAD

**Issue by kelvin195eclipse** [nodeWechat/wechat4u#231]
大家好，我想在MySQL资料库储存用户的资料，并用一个ID来追踪每一位用户，我知道UserName及用户昵称会随时变更，请问有没有办法获取任何一个固定的ID或其他方式来？让我之后可以查找这些用户

谢谢！

**Comment by spacelan** [comment]
可以给好友设置备注

**Comment by kelvin195eclipse** [comment]
请问可以大概描述如何设置备注和获取备注吗？谢谢~

**Comment by spacelan** [comment]
https://github.com/nodeWechat/wechat4u/pull/121

备注名是 `contact.RemarkName`

**Comment by kelvin195eclipse** [comment]
好的谢谢你！
