### ISSUE TITLE
现在返回通讯录中好友的微信号是否已经屏蔽

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#232]
![image](https://user-images.githubusercontent.com/22805853/28805334-d8d4c12c-769b-11e7-88a2-295cab42f812.png)

**Comment by jiaojunjiaojun** [comment]
@spacelan

**Comment by spacelan** [comment]
已经屏蔽了

而且用微信号作为`UserName`直接发消息的方法也失效了
