### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by heekah7** [nodeWechat/wechat4u#234]
SyntaxError: Invalid or unexpected token
    at /Users/hoi2/Desktop/qwerty/backend/node_modules/wechat4u/lib/core.js:362:19

同步时有时会发生这个错误，特别是对方打字的时候。我把core.js 362 + 363删除就解除了危机。

**Comment by spacelan** [comment]
正常情况下，这里应该是返回一段 js 的，然后最近腾讯搞鬼，有一定几率返回一段奇怪的数据，所以这里把奇怪的数据当做 js 执行的时候就异常了

你能够帮我们提交一个pr来修复这个问题么？

**Comment by spacelan** [comment]
https://github.com/nodeWechat/wechat4u/pull/235
