### ISSUE TITLE
无法获取群内用户昵称

### ISSUE THREAD

**Issue by kelvin195eclipse** [nodeWechat/wechat4u#237]
你好，以下是我的程序源码及结果。
我无法从Content里或MemberList里获取群内用户昵称，就连MemberList里所有的用户资料都是空，只获取到UserName，求解救谢谢。

![code](https://user-images.githubusercontent.com/18455592/29109570-0df0ab7a-7d16-11e7-8949-e5240608aad0.jpg)

![output](https://user-images.githubusercontent.com/18455592/29109578-1651ff26-7d16-11e7-9d43-f1eb50d1583b.jpg)

备注：改群内用户不是机器人好友。这个程序是要获取非好友群内昵称(Group Alias)。

**Comment by spacelan** [comment]
尝试用这个方法获取详细信息https://github.com/nodeWechat/wechat4u#botbatchgetcontactcontacts

**Comment by kelvin195eclipse** [comment]
好的谢谢，我试试看

**Comment by kelvin195eclipse** [comment]
请问EncryChatRoomId是群的UserName吗？(开始于@@的编码)

**Comment by spacelan** [comment]
和UserName是不一样的

**Comment by kelvin195eclipse** [comment]
请问这里 https://github.com/nodeWechat/wechat4u#botbatchgetcontactcontacts 所指的群信息是非是这个？

![prob](https://user-images.githubusercontent.com/18455592/29111845-88a10aa6-7d1e-11e7-9439-c207e184e288.jpg)

**Comment by kelvin195eclipse** [comment]
找到了，但是得到空。

![prob](https://user-images.githubusercontent.com/18455592/29114121-d0c800ee-7d25-11e7-984b-60ed32000d11.jpg)

**Comment by kelvin195eclipse** [comment]
得到EncryChatRoomId了谢谢，我先造尝试获取群用户资料

**Comment by kelvin195eclipse** [comment]
我知道问题所在了，机器人户口必须在群内的"Save to Contacts"设定为开启，这样一来bot.contacts[<群UserName>]就获取到群用户资料了。

非常谢谢！

**Comment by spacelan** [comment]
如果单纯想获取DisplayName或RemarkName，应该只需要
```js
bot.batchGetContact([{UserName: xxx}])
```
xxx为群的UserName，然后MemberList里就会有群成员的基础信息了

**Comment by kshan** [comment]
现在用了也是这样的情况，有些群有昵称信息，有些群就没有，还没排查出原因。

**Comment by spacelan** [comment]
手动调用的核心api直接取返回结果，不会触发事件

**Comment by kshan** [comment]
看源码内部也都执行了 batchGetContact 的方法，不知道为什么输出 msg.content 的时候，有些就没有显示昵称的，将群存为通讯录的时候昵称就正常，但偶尔有一些非好友的成员也是得不到昵称。

手动执行 batchGetContact 返回的 MemberList 里有昵称信息，但没发现有头像信息，这个是没法取到吗

**Comment by kelvin195eclipse** [comment]
尝试把群储存为联系人"Save to Contacts"了再获取群内用户，我以这个方式解决了这个问题哦

**Comment by spacelan** [comment]
@kshan 内部执行的`batchGetContact`只获取了群详细信息，而没有获取群成员详细信息
