### ISSUE TITLE
[功能请求] 可否考虑添加：短时间断开自动登陆的功能

### ISSUE THREAD

**Issue by kryss** [nodeWechat/wechat4u#239]
[这里有相关功能的代码](https://github.com/littlecodersh/ItChat/blob/bb853dfd27a8c3a8a3e0fe247b9a20a5787947b7/itchat/components/hotreload.py)，但是我是初学者不知道怎么加入到这个项目里面。
多谢

**Comment by spacelan** [comment]
早就实现这个功能了

https://github.com/nodeWechat/wechat4u/blob/master/run-core.js#L13-L17
https://github.com/nodeWechat/wechat4u/blob/master/run-core.js#L21-L26
https://github.com/nodeWechat/wechat4u/blob/master/run-core.js#L45-L49

这是一个简单的例子

你可以把`botData`保存在任意位置
