### ISSUE TITLE
哪个字段判断对方是未添加的好友

### ISSUE THREAD

**Issue by kshan** [nodeWechat/wechat4u#240]
想实现的是陌生人加机器人为好友后，机器人自动添加对方为好友。
因为机器人设置了免验证通过请求，这样还会触发好友请求这个事件来响应吗？
如果不能响应，现在想到的是，收到陌生人的信息后判断对方是否自己好友，不是就添加。

**Comment by kshan** [comment]
对比一下信息先

**Comment by spacelan** [comment]
陌生人不发消息好象是收不到事件的

contact结构里有一个字段是表示陌生人的，我忘了，你可以研究一下
