### ISSUE TITLE
某些户口扫描二维码登录突然出现错误

### ISSUE THREAD

**Issue by kelvin195eclipse** [nodeWechat/wechat4u#244]
您好，我的程序一直都很顺利地被我所有微信号登入及操作，并没有做到任何更改
直到最近，我的其中一个微信号登入时，在扫描二维码后出现以下错误：
![screen shot 2017-09-02 at 9 30 pm](https://user-images.githubusercontent.com/18455592/29995898-e10c69ae-9026-11e7-822f-e6978789dacd.jpg)

这是我的源码，可是应该没什么问题，因为其他的微信号都成功登入。
![screen shot 2017-09-02 at 9 44 pm](https://user-images.githubusercontent.com/18455592/29995971-2456c3ca-9028-11e7-9193-d5423e71b1c9.jpg)

目前我有三个微信号，全都没被封号，但只有这个微信号登入时出现此错误，其他两个正常操作。
请问是什么问题？

谢谢！

**Comment by kelvin195eclipse** [comment]
找到问题了，我也无法登入网页微信，出现此错误：
![screen shot 2017-09-02 at 9 59 pm](https://user-images.githubusercontent.com/18455592/29996066-13af8104-902a-11e7-91b8-8023c33026cb.jpg)

**Comment by ywwhack** [comment]
@kelvin195eclipse 大概半个多月前我的也突然登不上了，登录网页版的时候提示账号异常，但是手机登录正常，目测是被封号了 - -

**Comment by spacelan** [comment]
这是微信在搞事情啊，只能谨慎一点用了

**Comment by isuoge** [comment]
好怕怕。封号会影响客户端登录么？

**Comment by kelvin195eclipse** [comment]
Best Regards,
KELVIN TEH

"Successions come from great passion and determination."

**Comment by kelvin195eclipse** [comment]
我的机器人所照成的封号是网端微信登录不到，但是手机端依然可以使用。

Best Regards,
KELVIN TEH

"Successions come from great passion and determination."

**Comment by spacelan** [comment]
@kelvin195eclipse 恩 是这样的  微信一直在封 web 端登录

**Comment by xiaokaike** [comment]
有什么办法解除么？
