### ISSUE TITLE
怎么样在vue nuxt 浏览器端 中 使用?

### ISSUE THREAD

**Issue by issmile** [nodeWechat/wechat4u#245]
在index.vue中
<script>
const Wechat = require('wechat4u')
let bot = new Wechat()
bot.start()
</script>

报错

 ERROR  Failed to compile with 1 errors                                         17:33:14

This dependency was not found:

* fs in ./node_modules/mime/mime.js

To install it, you can run: npm install --save fs

**Comment by kshan** [comment]
参考这个 issue 吧
https://github.com/nodeWechat/wechat4u/issues/133
