### ISSUE TITLE
新用户扫码登录失败

### ISSUE THREAD

**Issue by MarsCWD** [nodeWechat/wechat4u#247]
提示：为了你的帐号安全，新注册的微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。  请问新注册账号需要多久之后才能登录？

**Comment by gaoryrt** [comment]
好像是微信灰度发布的一个限制，v2ex 有讨论：https://www.v2ex.com/t/391393

**Comment by spacelan** [comment]
这个问题出来一段时间了，老帐号被发现异常使用 web api 后也会被封

目前来看，偶尔用用 web api，并且不做大量群管理是不会被封的
