### ISSUE TITLE
我们能否获取群发助手的消息

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#253]
我们能否获取群发助手发出去的消息

**Comment by jiaojunjiaojun** [comment]
@spacelan

**Comment by udbmnm** [comment]
@jiaojunjiaojun  获取消息是最基本的功能

**Comment by jiaojunjiaojun** [comment]
一般的消息能获取到，但是用户群发助手发出去的消息获取不到

**Comment by jiaojunjiaojun** [comment]
![image](https://user-images.githubusercontent.com/22805853/32031385-7f7d90dc-ba33-11e7-8f7d-2a45f563bac7.png)
像这种发送方式

**Comment by udbmnm** [comment]
你登录网页版能不能看到消息

**Comment by jiaojunjiaojun** [comment]
也看不到消息

**Comment by udbmnm** [comment]
如果网页版接口什么都没有那就不行了

**Comment by jiaojunjiaojun** [comment]
谢谢

**Comment by spacelan** [comment]
感谢 @udbmnm
