### ISSUE TITLE
获取音乐消息上显示的图片

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#259]
![image](https://user-images.githubusercontent.com/22805853/33060120-21cd496a-ced2-11e7-9511-7e54ef15fea5.png)

**Comment by jiaojunjiaojun** [comment]
@spacelan ,谢谢

**Comment by oraoto** [comment]
可以用`getMsgImg`同样的接口，`type`改为`slave`。

**Comment by jiaojunjiaojun** [comment]
@oraoto 谢谢，我试试

**Comment by jiaojunjiaojun** [comment]
@oraoto 管用，不错

**Comment by spacelan** [comment]
感谢 @oraoto
