### ISSUE TITLE
getDoc有时返回空数据

### ISSUE THREAD

**Issue by lwpassvoice** [nodeWechat/wechat4u#263]
{"data":{"type":"Buffer","data":[]},"type":"application/octet-stream"} 

上传的36m的文件

**Comment by jiaojunjiaojun** [comment]
@lwpassvoice  你那儿能传超过1M的文件吗

**Comment by lwpassvoice** [comment]
@jiaojunjiaojun 可以的

**Comment by jiaojunjiaojun** [comment]
@lwpassvoice 我一直报那个错误
![image](https://user-images.githubusercontent.com/22805853/33419361-fc4e348c-d5e4-11e7-9ed6-df36d4770066.png)

**Comment by spacelan** [comment]
好久没看微信代码了，可能协议有变化吧
