### ISSUE TITLE
重新扫码登录会导致toUserName变化

### ISSUE THREAD

**Issue by figozhu** [nodeWechat/wechat4u#269]
1. 好友发来消息，把这时的FromUserName保存起来。

2. 关闭进程时间长了，再启动，读取配置重新登录会失败，需要重新扫码登录。

3. 按照之前步骤1保存的FromUserName去主动推送消息会失败（这时，步骤1的好友再发消息过来，发现FromUserName已经变了）

**Comment by oraoto** [comment]
每次登录都会UserName都是会变化的，如果要确定好友身份，只能用备注。

**Comment by figozhu** [comment]
了解了
