### ISSUE TITLE
如何标识群主

### ISSUE THREAD

**Issue by IGUIZP** [nodeWechat/wechat4u#276]

**Comment by IGUIZP** [comment]
bot.opLog返回数据没有，是不是屏蔽了

**Comment by spacelan** [comment]
应该是屏蔽了，你可以看看有没有其他字段能标识群主

发自我的 iPhone

**Comment by IGUIZP** [comment]
谢谢， contacts-updated事件监听中可以查询到ChatRoomOwner：这个值是成员username目测会改变，希望做到唯一确定群和群主以及群成员
