### ISSUE TITLE
怎么用

### ISSUE THREAD

**Issue by zaoqi-unsafe** [nodeWechat/wechat4u#278]
Your environment has been set up for using Node.js 10.15.1 (ia32) and npm.

C:\Users\zaoqi>cd bot

C:\Users\zaoqi\bot>node bot.js
[/event] 建立連線中, 請稍後...
[/api] 建立連線中, 請稍後...
[/event] 連線成功 ヽ(✿ﾟ▽ﾟ)ノ 蛆蛆1個嘗試
[/api] 連線成功 ヽ(✿ﾟ▽ﾟ)ノ 蛆蛆1個嘗試
今天又是複讀複讀的一天 ｡:.ﾟヽ(*´∀`)ﾉﾟ.:｡
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄▀ ▀ ▀ ██▀█▄▄█ ▄▄▄▄▄ █
█ █   █ █   █▀▄ ▀ ▀ ▄▀█ █   █ █
█ █▄▄▄█ █▄█▀ ▄▄▀▄█▀▀ ██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ █ █▄▀ ▀▄▀▄█▄▄▄▄▄▄▄█
█ ▄ ▄▀█▄█▄█ ▄  ▄▀ ▄ ▀█ ▀▀ ▄▄█ █
█ ▄▄  ▀▄ ▀  ▄▄▀██▄█▀█ ▄▄█▀█▄▄▀█
██▄▄ ▀ ▄█▀▄▄▀ █  ▀▄█ █▄▀██▄ ▀▀█
██▀█▄█ ▄▄ ▀▄ █▄▀▀ ▄▄▄▄ ▀  █▄ ▄█
█▄▀█ ▄█▄▀▄ ▀█▄▄ ██▀▄▄  █ ▄ ▀ ██
█▄█▄██▀▄▄   ▀██▄ █▀▀█▀▀▀▄▀█ ███
██▄██▄▄▄█ ▄▄██▀▀ ▀ ▀▀ ▄▄▄   ▀▀█
█ ▄▄▄▄▄ ██  ▀▀▀▀█ █ ▄ █▄█  █▄██
█ █   █ █▀ ▄ █▀▀█▀▄█▀  ▄  ▀▄▄ █
█ █▄▄▄█ █ █▀█ ▀▄█▀█ ▄ ██▄▀▀▄▀▄█
█▄▄▄▄▄▄▄█▄▄█▄███▄███▄▄▄██▄██▄██

二维码链接： https://login.weixin.qq.com/qrcode/IZDeG03_LA==
错误： { AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (C:\Users\zaoqi\node_modules\wechat4u\lib\util\global.js:69:24)
    at C:\Users\zaoqi\node_modules\wechat4u\lib\core.js:187:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: 1,
  expected: 0,
  operator: '==',
  response:
   { status: 200,
     statusText: 'OK',
     headers:
      { connection: 'close',
        'content-type': 'text/plain',
        'strict-transport-security': 'max-age=31536000',
        'content-length': '650' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 60000,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        Cookie: [Object],
        httpAgent: false,
        httpsAgent: false,
        method: 'POST',
        url: 'https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxinit',
        params: [Object],
        data:
         '{"BaseRequest":{"Uin":null,"Sid":"","Skey":"","DeviceID":"e490388837866031"}}' },
     data:
      { BaseResponse: [Object],
        Count: 0,
        ContactList: [],
        SyncKey: [Object],
        User: [Object],
        ChatSet: '',
        SKey: '',
        ClientVersion: 0,
        SystemTime: 0,
        GrayScale: 0,
        InviteStartCount: 0,
        MPSubscribeMsgCount: 0,
        MPSubscribeMsgList: [],
        ClickReportInterval: 0 } },
  tips: '微信初始化失败' }
登出成功
(node:11756) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink './sync-data.json'
    at Object.unlinkSync (fs.js:952:3)
    at Wechat.bot.on (C:\Users\zaoqi\bot\bot.js:113:6)
    at Wechat.emit (events.js:189:13)
    at Wechat.stop (C:\Users\zaoqi\node_modules\wechat4u\lib\wechat.js:277:12)
    at C:\Users\zaoqi\node_modules\wechat4u\lib\wechat.js:239:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
C:\Users\zaoqi\bot>

**Comment by zaoqi-unsafe** [comment]
function onmsg_qq(data){
	
}
(function(){
const { CQWebSocket } = require('cq-websocket')
const bot = new CQWebSocket({
    host: "127.0.0.1",
    port: 6700,
    baseUrl: "",
    qq: "2679125746",
    accessToken: ""
  })
  
  // 設定訊息監聽
  bot
    // 連線例外處理
    .on('socket.error', console.error)
    .on('socket.connecting', (wsType) => console.log('[%s] 建立連線中, 請稍後...', wsType))
    .on('socket.connect', (wsType, sock, attempts) => console.log('[%s] 連線成功 ヽ(✿ﾟ▽ﾟ)ノ 蛆蛆%d個嘗試', wsType, attempts))
    .on('socket.failed', (wsType, attempts) => console.log('[%s] 連線失敗 。･ﾟ･(つд`ﾟ)･ﾟ･ [丑%d] 對噗起', wsType, attempts))
    .on('api.response', (resObj) => console.log('伺服器響應: %O', resObj))
    .on('socket.close', (wsType, code, desc) => console.log('[%s] 連線關閉(%d: %s)', wsType, code, desc))
    .on('ready', () => console.log('今天又是複讀複讀的一天 ｡:.ﾟヽ(*´∀`)ﾉﾟ.:｡'))

    // 聽取私人信息
    .on('message.private', (e, context) => {
      console.log('叮咚 ✿ private')
      console.log(context)
    /*
      // 以下提供三種方式將原訊息以原路送回
      switch (Date.now() % 3) {
        case 0:
          // 1. 調用 CoolQ HTTP API 之 send_msg 方法
          bot('send_msg', context)
          break
        case 1:
          // 2. 或者透過返回值快速響應
          return context.message
        case 2:
          // 3. 或者透過CQEvent實例，先獲取事件處理權再設置響應訊息
          e.stopPropagation()
          e.setMessage(context.message)
      }*/
    })
	.on('message.group', (e, context) => {
		console.log('叮咚 ✿ group')
      console.log(context)
	  onmsg_qq({
		  message: context.message,
		  sender: {
			  nick: context.sender.nick
		  }
	  })
	})
  
  bot.connect()
})();
(function(){
	const Wechat = require('wechat4u')
const qrcode = require('qrcode-terminal')
const fs = require('fs')
const request = require('request')


let bot
/**
 * 尝试获取本地登录数据，免扫码
 * 这里演示从本地文件中获取数据
 */
try {
  bot = new Wechat(require('./sync-data.json'))
} catch (e) {
  bot = new Wechat()
}
/**
 * 启动机器人
 */
if (bot.PROP.uin) {
  // 存在登录数据时，可以随时调用restart进行重启
  bot.restart()
} else {
  bot.start()
}
/**
 * uuid事件，参数为uuid，根据uuid生成二维码
 */
bot.on('uuid', uuid => {
  qrcode.generate('https://login.weixin.qq.com/l/' + uuid, {
    small: true
  })
  console.log('二维码链接：', 'https://login.weixin.qq.com/qrcode/' + uuid)
})
/**
 * 登录用户头像事件，手机扫描后可以得到登录用户头像的Data URL
 */
bot.on('user-avatar', avatar => {
  console.log('登录用户头像Data URL：', avatar)
})
/**
 * 登录成功事件
 */
bot.on('login', () => {
  console.log('登录成功')
  // 保存数据，将数据序列化之后保存到任意位置
  fs.writeFileSync('./sync-data.json', JSON.stringify(bot.botData))
})
/**
 * 登出成功事件
 */
bot.on('logout', () => {
  console.log('登出成功')
  // 清除数据
  fs.unlinkSync('./sync-data.json')
})
/**
 * 联系人更新事件，参数为被更新的联系人列表
 */
bot.on('contacts-updated', contacts => {
  console.log(contacts)
  console.log('联系人数量：', Object.keys(bot.contacts).length)
})
/**
 * 错误事件，参数一般为Error对象
 */
bot.on('error', err => {
  console.error('错误：', err)
})
/**
 * 如何发送消息
 */
bot.on('login', () => {
  /**
   * 演示发送消息到文件传输助手
   * 通常回复消息时可以用 msg.FromUserName
   */
  let ToUserName = 'filehelper'

  /**
   * 发送文本消息，可以包含emoji(😒)和QQ表情([坏笑])
   */
  bot.sendMsg('发送文本消息，可以包含emoji(😒)和QQ表情([坏笑])', ToUserName)
    .catch(err => {
      bot.emit('error', err)
    })

  /**
   * 通过表情MD5发送表情
   */
  bot.sendMsg({
    emoticonMd5: '00c801cdf69127550d93ca52c3f853ff'
  }, ToUserName)
    .catch(err => {
      bot.emit('error', err)
    })

  /**
   * 以下通过上传文件发送图片，视频，附件等
   * 通用方法为入下
   * file为多种类型
   * filename必填，主要为了判断文件类型
   */
  // bot.sendMsg({
  //   file: Stream || Buffer || ArrayBuffer || File || Blob,
  //   filename: 'bot-qrcode.jpg'
  // }, ToUserName)
  //   .catch(err => {
  //     bot.emit('error',err)
  //   })

  /**
   * 发送图片
   */
  bot.sendMsg({
    file: request('https://raw.githubusercontent.com/nodeWechat/wechat4u/master/bot-qrcode.jpg'),
    filename: 'bot-qrcode.jpg'
  }, ToUserName)
    .catch(err => {
      bot.emit('error', err)
    })

  /**
   * 发送表情
   */
  bot.sendMsg({
    file: fs.createReadStream('./media/test.gif'),
    filename: 'test.gif'
  }, ToUserName)
    .catch(err => {
      bot.emit('error', err)
    })

  /**
   * 发送视频
   */
  bot.sendMsg({
    file: fs.createReadStream('./media/test.mp4'),
    filename: 'test.mp4'
  }, ToUserName)
    .catch(err => {
      bot.emit('error', err)
    })

  /**
   * 发送文件
   */
  bot.sendMsg({
    file: fs.createReadStream('./media/test.txt'),
    filename: 'test.txt'
  }, ToUserName)
    .catch(err => {
      bot.emit('error', err)
    })

  /**
   * 发送撤回消息请求
   */
  bot.sendMsg('测试撤回', ToUserName)
     .then(res => {
       // 需要取得待撤回消息的MsgID
       return bot.revokeMsg(res.MsgID, ToUserName)
     })
     .catch(err => {
       console.log(err)
     })
})
/**
 * 如何处理会话消息
 */
bot.on('message', msg => {
  /**
   * 获取消息时间
   */
  console.log(`----------${msg.getDisplayTime()}----------`)
  /**
   * 获取消息发送者的显示名
   */
  console.log(bot.contacts[msg.FromUserName].getDisplayName())
  /**
   * 判断消息类型
   */
  switch (msg.MsgType) {
    case bot.CONF.MSGTYPE_TEXT:
      /**
       * 文本消息
       */
      console.log(msg.Content)
      break
    case bot.CONF.MSGTYPE_IMAGE:
      /**
       * 图片消息
       */
      console.log('图片消息，保存到本地')
      bot.getMsgImg(msg.MsgId).then(res => {
        fs.writeFileSync(`./media/${msg.MsgId}.jpg`, res.data)
      }).catch(err => {
        bot.emit('error', err)
      })
      break
    case bot.CONF.MSGTYPE_VOICE:
      /**
       * 语音消息
       */
      console.log('语音消息，保存到本地')
      bot.getVoice(msg.MsgId).then(res => {
        fs.writeFileSync(`./media/${msg.MsgId}.mp3`, res.data)
      }).catch(err => {
        bot.emit('error', err)
      })
      break
    case bot.CONF.MSGTYPE_EMOTICON:
      /**
       * 表情消息
       */
      console.log('表情消息，保存到本地')
      bot.getMsgImg(msg.MsgId).then(res => {
        fs.writeFileSync(`./media/${msg.MsgId}.gif`, res.data)
      }).catch(err => {
        bot.emit('error', err)
      })
      break
    case bot.CONF.MSGTYPE_VIDEO:
    case bot.CONF.MSGTYPE_MICROVIDEO:
      /**
       * 视频消息
       */
      console.log('视频消息，保存到本地')
      bot.getVideo(msg.MsgId).then(res => {
        fs.writeFileSync(`./media/${msg.MsgId}.mp4`, res.data)
      }).catch(err => {
        bot.emit('error', err)
      })
      break
    case bot.CONF.MSGTYPE_APP:
      if (msg.AppMsgType == 6) {
        /**
         * 文件消息
         */
        console.log('文件消息，保存到本地')
        bot.getDoc(msg.FromUserName, msg.MediaId, msg.FileName).then(res => {
          fs.writeFileSync(`./media/${msg.FileName}`, res.data)
          console.log(res.type);
        }).catch(err => {
          bot.emit('error', err)
        })
      }
      break
    default:
      break
  }
})
/**
 * 如何处理红包消息
 */
bot.on('message', msg => {
  if (msg.MsgType == bot.CONF.MSGTYPE_SYS && /红包/.test(msg.Content)) {
    // 若系统消息中带有‘红包’，则认为是红包消息
    // wechat4u并不能自动收红包
  }
})
/**
 * 如何处理转账消息
 */
bot.on('message', msg => {
  if (msg.MsgType == bot.CONF.MSGTYPE_APP && msg.AppMsgType == bot.CONF.APPMSGTYPE_TRANSFERS) {
    // 转账
  }
})
/**
 * 如何处理撤回消息
 */
bot.on('message', msg => {
  if (msg.MsgType == bot.CONF.MSGTYPE_RECALLED) {
    // msg.Content是一个xml，关键信息是MsgId
    let MsgId = msg.Content.match(/<msgid>(.*?)<\/msgid>.*?<replacemsg><!\[CDATA\[(.*?)\]\]><\/replacemsg>/)[0]
    // 得到MsgId后，根据MsgId，从收到过的消息中查找被撤回的消息
  }
})
/**
 * 如何处理好友请求消息
 */
bot.on('message', msg => {
  if (msg.MsgType == bot.CONF.MSGTYPE_VERIFYMSG) {
    bot.verifyUser(msg.RecommendInfo.UserName, msg.RecommendInfo.Ticket)
      .then(res => {
        console.log(`通过了 ${bot.Contact.getDisplayName(msg.RecommendInfo)} 好友请求`)
      })
      .catch(err => {
        bot.emit('error', err)
      })
  }
})
/**
 * 如何直接转发消息
 */
bot.on('message', msg => {
  // 不是所有消息都可以直接转发
  bot.forwardMsg(msg, 'filehelper')
    .catch(err => {
      bot.emit('error', err)
    })
})
/**
 * 如何获取联系人头像
 */
bot.on('message', msg => {
  bot.getHeadImg(bot.contacts[msg.FromUserName].HeadImgUrl).then(res => {
    fs.writeFileSync(`./media/${msg.FromUserName}.jpg`, res.data)
  }).catch(err => {
    bot.emit('error', err)
  })
})
})();

**Comment by chelsh** [comment]
const Wechat = require('wechat4u')
let bot = new Wechat()
bot.start();

bot.on('login', () => {

    let ToUserName = 'filehelper';

    /**

     * 发送文本消息，可以包含emoji和QQ表情([坏笑])
     */
    bot.sendMsg('发送文本消息，可以包含emoji(😒)和QQ表情([坏笑])', ToUserName).catch(err => {
        bot.emit('error', err);
    });
});



----网页版本登录后，没有自动发送消息啊？要怎么用呢

**Comment by chelsh** [comment]
要写在网页里面，然后打开网页？

**Comment by chelsh** [comment]
直接 node test.js不行吗？

**Comment by spacelan** [comment]
这个都是要写代码控制的

这里有个样例https://github.com/nodeWechat/wechat4u/blob/master/run-core.js
