### ISSUE TITLE
群消息中谁发送的消息疑问

### ISSUE THREAD

**Issue by dadaa1** [nodeWechat/wechat4u#280]
我拿到 msg.Content,这里面包含发送者和内容，他们之间时通过:\n来分割，但是发送者的可能是nickname还有可能是username，我想知道什么时候是nickname还是username？

**Comment by spacelan** [comment]
https://github.com/nodeWechat/wechat4u/blob/master/src/interface/message.js#L39

可能这里的代码对你有用

**Comment by dadaa1** [comment]
你的意思是在contact对象上查找么？
我打印了下contact,MemberList有时候nickname是存在的，有时候都是空值，不确定什么时候是空值

**Comment by dadaa1** [comment]
@spacelan 是不是微信服务器返回的就是空呀

**Comment by spacelan** [comment]
这些值是微信通过消息推送过来的，可以尝试调用一些群控制接口触发微信推送

比如之前可以通过调用置顶API来触发，现在这个API好像不能用了

**Comment by dadaa1** [comment]
好的，我懂了，谢谢你。
那我只能本地维护一个map,每次接受新的信息去给它更新map了
