### ISSUE TITLE
如果登陆了多个账号,如何同时监听多个账号的新消息?

### ISSUE THREAD

**Issue by nightwhite** [nodeWechat/wechat4u#317]
是可以统一监听还是必须每一个账号启一个进程去监听

**Comment by spacelan** [comment]
可以new多个bot


在 2023年2月16日，03:59，nightwhite ***@***.***> 写道：

﻿

是可以统一监听还是必须每一个账号启一个进程去监听

**Comment by nightwhite** [comment]
请问某一个bot.stop() 后,进程会自动释放该bot的监听的内存占用吗

**Comment by spacelan** [comment]
会的

**Comment by nightwhite** [comment]
非常感谢
