### ISSUE TITLE
axios超时状态未捕获成功

### ISSUE THREAD

**Issue by moushicheng** [nodeWechat/wechat4u#330]
<img width="1012" alt="image" src="https://github.com/nodeWechat/wechat4u/assets/54257412/3672415e-0f8c-4971-b4a8-3f18fd3ae1bd">
溯源发现出在这个库里

<img width="551" alt="image" src="https://github.com/nodeWechat/wechat4u/assets/54257412/7c17ff88-d3a6-4c79-9d4c-481896b73197">

但由于调用堆栈缺失，无法排查到是哪里超时，还在努力

## 其他
我也会一直跟进，继续排查是哪个api超时，有进展直接评论同步

**Comment by my19940202** [comment]
后来有定位到原因吗

**Comment by my19940202** [comment]
> <img alt="image" width="1012" src="https://private-user-images.githubusercontent.com/54257412/278215156-3672415e-0f8c-4971-b4a8-3f18fd3ae1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDQyNzAsIm5iZiI6MTcwOTU0Mzk3MCwicGF0aCI6Ii81NDI1NzQxMi8yNzgyMTUxNTYtMzY3MjQxNWUtMGY4Yy00OTcxLWI0YTgtM2YxOGZkM2FlMWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5MTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMGY0OTA1YzUxMjY0MTEwNDVlMjgzYjgyNDA4YjI5ZTAzOWJjM2E1YTc2NWJmYzQwNjA0ZjBlNjkwNzdmYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CN53YAhUlPa8CYJYGk56KV5vbVyD57zO90zaVjsj0Kc"> 溯源发现出在这个库里 <img alt="image" width="551" src="https://private-user-images.githubusercontent.com/54257412/278215311-7c17ff88-d3a6-4c79-9d4c-481896b73197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDQyNzAsIm5iZiI6MTcwOTU0Mzk3MCwicGF0aCI6Ii81NDI1NzQxMi8yNzgyMTUzMTEtN2MxN2ZmODgtZDNhNi00Yzc5LTlkNGMtNDgxODk2YjczMTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5MTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YjkwOWQzNzVkMmQ0NjgwYjBiMGFlNDBhODU1ZDNkMTQwZDAzMTc0MTRhMDI0OTIxMDcxYWU0YWNjZGJjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._QyZsv6zau4pP6jntjFvn9K7qb6ipPLDeMIQIIhLDK8">
> 但由于调用堆栈缺失，无法排查到是哪里超时，还在努力
> 
> ## 其他
> 我也会一直跟进，继续排查是哪个api超时，有进展直接评论同步

大佬后来有定位原因吗

**Comment by allforone** [comment]
有定位到不
