### ISSUE TITLE
登录失败问题

### ISSUE THREAD

**Issue by zyp1573** [nodeWechat/wechat4u#336]
一直用一个小号作为机器人，正常登录大概一个多月，今天突然没了心跳，然后无论怎么扫码都是走到登录失败的回调，代码没问题，相同代码换另一个微信号可以正常登录。

**Comment by spacelan** [comment]
试一下微信网页版能不能登陆，可能就是被微信ban了

**Comment by zyp1573** [comment]
> 试一下微信网页版能不能登陆，可能就是被微信ban了

感谢回复，这个微信号一直都登录不了网页版的[https://wx.qq.com]。我又重试了几次，又可以正常登录了，感觉应该是被限制一些时间不允许登录这个web版。
