### ISSUE TITLE
有几处问题

### ISSUE THREAD

**Issue by fanly** [nodeWechat/wechat4u#38]
wechat CheckScan +430ms
  wechat ReferenceError: debug is not defined
    at /Users/wuhaiping/git/learning/new_weixin/wechatBot/node_modules/.npminstall/wechat4u/0.3.0/wechat4u/lib/utils.js:92:7
    at String.replace (native)
    at convertEmoji (/Users/wuhaiping/git/learning/new_weixin/wechatBot/node_modules/.npminstall/wechat4u/0.3.0/wechat4u/lib/utils.js:78:12)
    at /Users/wuhaiping/git/learning/new_weixin/wechatBot/node_modules/.npminstall/wechat4u/0.3.0/wechat4u/lib/wechat.js:303:34
    at process._tickCallback (node.js:406:9) +9s
  wechat 启动失败 +5ms [Error: 获取通讯录失败]
  app 关闭登陆失败连接 +2ms 1
  app 新连接 +2s 2
  wechat CheckScan +27ms
  wechat Error: 扫描状态code错误: 408
    at /Users/wuhaiping/git/learning/new_weixin/wechatBot/node_modules/.npminstall/wechat4u/0.3.0/wechat4u/lib/wechat.js:138:17
    at process._tickCallback (node.js:406:9)

**Comment by stonexer** [comment]
不好意思，这是 0.3.0 的 bug。utils.js 里没有 require debug 。手动加上或者去掉 debug 都行。

convertEmoji 的异常原因还不知道有没有什么对策。

**Comment by spacelan** [comment]
大哥赶紧发patch啊😂

**Comment by stonexer** [comment]
75df64f8f5b841155113f7bb0caac04b1a3a9e36

已经修复了
