### ISSUE TITLE
如何保持长连接

### ISSUE THREAD

**Issue by enforceway** [nodeWechat/wechat4u#43]
如何保持长连接?保持登录后的微信用户在wechat4u node端一直在线。可以接收联系人发送来的信息

**Comment by spacelan** [comment]
理论上只要不在手机上登出网页版，wechat4u就会一直在线

所以你是在哪种情况下发现wechat4u被下线了？我们排查一下问题

**Comment by enforceway** [comment]
我大概描述一下情况哈。后台出现了相应联系人的username后，后台一直使用这个username给这个联系人发送消息。最近一次这样做，结果是，连续发送了775条，就无法发送了，同时推断手机上面的‘登出网页版’按钮也小时了。因为这样测试，已经有好多次。

**Comment by enforceway** [comment]
775条，延续了6.5个小时。不过这个时长是随机的。最短也有1小时就被迫下线了。

**Comment by stonexer** [comment]
稳定性一直是个问题，再研究研究微信网页版的源码吧。。

**Comment by enforceway** [comment]
话说，这个是不是微信人家就没做彻底?我尝试过，登录wx.qq.com然后留着放置一天，同时微信客户端不要去点‘退出微信网页版’。结果第二天(当然时间确实比6.5个小时长多了)，一样被迫下线，同时在wx.qq.com登录的页面刷新后也退出了。

**Comment by stonexer** [comment]
应该就是没那么强的稳定性吧，网页版也不太需要长期稳定。先追上它的稳定性就很开心了😂

**Comment by enforceway** [comment]
同意，严重同意，嘿嘿

**Comment by cbwang2016** [comment]
我觉得网页版被迫下线应该是cookie过期的原因

**Comment by klausgao** [comment]
最近用Chrome测试过微信网页版，发现也是很快就自动退出了，后来加了个Chrome的定时刷新的插件，大概5分钟刷新一次，同时Chrome的窗口保持最前端，就感觉好多了，试过从上午开着放到下午，也没掉线。另外不懂你们发现没有，网页版，如果窗体不在前端，是不会去获取最新消息的。

**Comment by spacelan** [comment]
@klausgao 晚上可以保持登录到早上，但是白天可能一会儿就掉线了。。
