### ISSUE TITLE
频繁 Error: 扫描状态code错误: 408

### ISSUE THREAD

**Issue by fanly** [nodeWechat/wechat4u#46]
wechat Receive  +1s 0 Message
新连接 88
  wechat Error: 扫描状态code错误: 408
    at wechat4u/wechat.js:148:15
    at process._tickCallback (node.js:412:9) +17s
  wechat 启动失败 +1ms [Error: 获取扫描状态信息失败]
  app 关闭登陆失败连接 +0ms 87
  wechat WebSync Normal +12s
wechat:err
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
getUUID:获取UUID失败
新连接 88

**Comment by stonexer** [comment]
居然 88 个连接么。

扫描状态 408 直接就是微信服务器返回的，可能是手机扫描失败或是服务器由于某种原因返回异常，咱这儿应该没法解决。
