### ISSUE TITLE
希望添加撤回消息的API

### ISSUE THREAD

**Issue by cbwang2016** [nodeWechat/wechat4u#49]
如题。如果能有个什么MySQL支持那就更好了╮(╯▽╰)╭

**Comment by stonexer** [comment]
MySQL 支持是指？有什么特别需要的么？

**Comment by yellowchanx** [comment]
你好，请问有撤回消息的接口吗？如何调用？

**Comment by stonexer** [comment]
@yellowchanx dev 分支已经支持撤回消息了。但关于 API 还没有确定下来，msg 的 content 大致结构如下：
`
<sysmsg type=\"revokemsg\">
  <revokemsg>
    <session>wxid_7313013130512</session>
    <oldmsgid>1636969782</oldmsgid>
    <msgid>6404350812340146699</msgid>
    <replacemsg>
      <![CDATA[ä½ æ’¤å›žäº†ä¸€æ¡æ¶ˆæ¯]]>
    </replacemsg>
  </revokemsg>
</sysmsg>
`
关于需不需要 parse 成 json ，需要哪些字段欢迎建议。

**Comment by yellowchanx** [comment]
@stonexer  可以支持这种方法调用吗？wechat.on('revokemsg', msg => {}) ，json的话，可以是撤回消息的用户信息+撤回的消息内容
