### ISSUE TITLE
无法登陆了 扫了就显示登录超时

### ISSUE THREAD

**Issue by superhos** [nodeWechat/wechat4u#55]
无法登陆了 扫了就显示登录超时 已经不能用了吗？

**Comment by superhos** [comment]
debug了下 是checkScan的时候socket hang up code :  'ECONNRESET' 了 是微信那边服务端拒绝了?

**Comment by fanly** [comment]
wechat:err
{ [Error: socket hang up] code: 'ECONNRESET' }
getUUID:获取UUID失败
wechat:err
{ [Error: socket hang up] code: 'ECONNRESET' }
getUUID:获取UUID失败

**Comment by stonexer** [comment]
是有这样的问题了，在研究是不是 API 有变化。

**Comment by spacelan** [comment]
#56

**Comment by spacelan** [comment]
#57 已修复
