### ISSUE TITLE
提起 Error:获取扫描状态信息失败

### ISSUE THREAD

**Issue by vimer** [nodeWechat/wechat4u#58]

**Comment by vimer** [comment]
如题

**Comment by vimer** [comment]
![image](http://ww2.sinaimg.cn/large/744e593bgw1f7z80p5xcbj20ow0be41j.jpg)

**Comment by spacelan** [comment]
找到问题了，axios版本没有在package.json里更新

手动升级到最新版本就好了

**Comment by vimer** [comment]
解决 谢谢
