### ISSUE TITLE
axios报错，有的微信号当做机器人没有任何问题，有的微信号就报下面错误

### ISSUE THREAD

**Issue by vimer** [nodeWechat/wechat4u#61]
￼![image](http://tmp.btclass.cn/881E8380-6632-43F9-BC8F-2FB3364C0568.png)

**Comment by spacelan** [comment]
是哪个请求呢

**Comment by vimer** [comment]
可能是入群的一些请求，另外有一些号获取不到所有群

**Comment by stonexer** [comment]
1. 有的微信号有问题可能是走了不同 route 的原因，比如 wx 和 wx2 的差异导致的。
2. 获取不到所有群，可以看下是不是没有保存该群到通讯录。

**Comment by vimer** [comment]
@stonexer 保存到通讯录了 还是获取不到

有的微信号走不通route导致的 那么怎么解决这个问题呢

**Comment by spacelan** [comment]
4.0版本可以获取没有保存到通讯录但是最近有过消息的群

**Comment by vimer** [comment]
@spacelan 我看4.0版本代码改了不少，之前还在用3.4.0版本

**Comment by vimer** [comment]
@stonexer 奇怪，微信版本一样，为什么不同微信号还会走不通的rouute，这个问题怎么解决呢

**Comment by vimer** [comment]
@spacelan @stonexer ![img](http://tmp.btclass.cn/F7ECBD53-73D2-47CE-8EF3-ADFAB0CC1AEF.png)

**Comment by vimer** [comment]
经测试，是时不时的会出现这个错误

**Comment by spacelan** [comment]
我明天看看哈

**Comment by spacelan** [comment]
大神把遇到的问题跟我们交流交流吧，一起来完善这个库

**Comment by vimer** [comment]
@spacelan 建议自己申请个新号进行测试。

**Comment by vimer** [comment]
@spacelan 给我开发者权限呗

**Comment by vimer** [comment]
@spacelan @stonexer 这个问题建议重视下哦

**Comment by spacelan** [comment]
这个503应该是微信服务器出的错吧，axios里只要不是2xx响应就当做error
