### ISSUE TITLE
发一个表情就出现狂刷，一直报ret code错误

### ISSUE THREAD

**Issue by moxiaobei2** [nodeWechat/wechat4u#62]
我发一个表情给自己，表情包的那种，或者图片等均出现狂刷的情况

**Comment by spacelan** [comment]
话说，网页版也是，发出一个表情之后要刷一会儿才停

不过ret code错误倒是有问题

**Comment by moxiaobei2** [comment]
但是这样我测试不了picture-message emotion-message以及其他功能哇

**Comment by spacelan** [comment]
这些接口4.0都有的。。只是没写文档出来

**Comment by spacelan** [comment]
对了，4.0还能发自定义表情

**Comment by moxiaobei2** [comment]
@spacelan 就是现在版本可用了吗？为啥我都弄不了咧。需要作什么配置吗？
