### ISSUE TITLE
当出现你登出了微信这个错误

### ISSUE THREAD

**Issue by vimer** [nodeWechat/wechat4u#65]
应该logout()下

**Comment by spacelan** [comment]
catch这个异常的方法里调用了logout

https://github.com/nodeWechat/wechat4u/blob/master/src/wechat.js#L347

**Comment by vimer** [comment]
@spacelan 这个是当err出现三次错误的时候才logout，但是我发现这个错误只要出现一次，整个服务就崩溃掉了。

**Comment by spacelan** [comment]
double check一下嘛，不过这样如果真的退出了大概会延时3秒触发事件
