### ISSUE TITLE
AttrStatus 这个属性是什么意思 ？

### ISSUE THREAD

**Issue by vimer** [nodeWechat/wechat4u#69]
{
    "Uin": 236008826,
    "UserName": "@912d2268c7e87688e5c8f33003b488f3adcfd3b4d25fcb9a271550bfc18a7328",
    "NickName": "膜法师",
    "AttrStatus": 4357,
    "PYInitial": "",
    "PYQuanPin": "",
    "RemarkPYInitial": "",
    "RemarkPYQuanPin": "",
    "MemberStatus": 0,
    "DisplayName": "",
    "KeyWord": ""
    }

**Comment by vimer** [comment]
@spacelan @stonexer  微信的UserName 每次启动和登入都是随机的，我想取这种固定id，目前发现AttrStatus是个固定的 但不知道这个id具体的作用

**Comment by spacelan** [comment]
UserName不是每个用户的UUID么？

**Comment by vimer** [comment]
@spacelan 是每个用户的uuid，不过每次服务重启后，uuid会变得，并不是固定的。

**Comment by spacelan** [comment]
好吧，但是AttrStatus这个属性的值再联系人会有重复

**Comment by vimer** [comment]
嗯，比较郁闷。
