### ISSUE TITLE
现在登录每次都返回 你登出了微信，麻烦查看下。

### ISSUE THREAD

**Issue by vimer** [nodeWechat/wechat4u#74]

**Comment by spacelan** [comment]
我更新了core分支

主要有两个文件`wechat.js`和`core.js`

`core.js`提供了微信API，储存了为了保持登录的必要信息。使用`core.js`必须手动进行同步

`wechat.js`继承了`core.js`，储存了联系人（包括大部分群）。提供了`start()`,`stop()`两个方法和一些事件，只需要调用`start()`就能保持登录，然后通过事件获取信息

你可以用`npm run core`和`npm run example`试试效果，在线版本也能用了

**Comment by jiaojunjiaojun** [comment]
还是登录没多久就退出了

**Comment by spacelan** [comment]
@jiaojunjiaojun 你是本地跑的还是测试服务器？

**Comment by spacelan** [comment]
@jiaojunjiaojun 
https://github.com/nodeWechat/wechat4u/tree/core
试试新版本

**Comment by jiaojunjiaojun** [comment]
@spacelan 我是在本地跑的
![image](https://cloud.githubusercontent.com/assets/22805853/19372053/181c3b12-91eb-11e6-93c0-69226f6805d4.png)

**Comment by jiaojunjiaojun** [comment]
@spacelan 
好像是微信把同步的线路改了

**Comment by spacelan** [comment]
你在core分支试试么

`DEBUG=core node run-core.js`

**Comment by jiaojunjiaojun** [comment]
是的，我就是切换到core分支运行的

**Comment by jiaojunjiaojun** [comment]
@spacelan 
DEBUG=core node run-core.js 这是什么意思，不是npm run example吗

**Comment by jiaojunjiaojun** [comment]
@spacelan 

我是切换到core分支，安装了npm install 直接运行npm run example对吗？谢谢

**Comment by spacelan** [comment]
`DEBUG=core node run-core.js`就是这命令

**Comment by jiaojunjiaojun** [comment]
![image](https://cloud.githubusercontent.com/assets/22805853/19374172/6887bafc-91fc-11e6-8525-2d794205a1cc.png)

**Comment by spacelan** [comment]
@jiaojunjiaojun 
win上用这个命令`set DEBUG=core,wechat && node run-core.js`

**Comment by jiaojunjiaojun** [comment]
@spacelan 
![image](https://cloud.githubusercontent.com/assets/22805853/19374709/5b6abcda-9200-11e6-85b2-8f544f12f1bf.png)

**Comment by spacelan** [comment]
能把log都贴出来么，我分析一下

**Comment by jiaojunjiaojun** [comment]
![image](https://cloud.githubusercontent.com/assets/22805853/19374842/7a1fb698-9201-11e6-923f-bdbbf3a3494a.png)

**Comment by jiaojunjiaojun** [comment]
![image](https://cloud.githubusercontent.com/assets/22805853/19374879/bfc0fd42-9201-11e6-8516-ef8b64c434a7.png)

**Comment by spacelan** [comment]
@jiaojunjiaojun 我没办法走wx2.qq.com这个服务器，但是我目测是cookie的问题，已经修复了，麻烦试一下

**Comment by vimer** [comment]
@spacelan 还是core这个分支

**Comment by jiaojunjiaojun** [comment]
@spacelan 没问题了，那master分支是不是也是这个问题

**Comment by spacelan** [comment]
恩，我会尽快更新

**Comment by jiaojunjiaojun** [comment]
@spacelan ,你好在不，我发送信息是为什么发送人取不到值
![image](https://cloud.githubusercontent.com/assets/22805853/19422832/ad510c04-944c-11e6-8378-6c228cdc7bc3.png)，谢谢

**Comment by spacelan** [comment]
@jiaojunjiaojun 
你在run-core.js里看看bot.user有没有值

**Comment by jiaojunjiaojun** [comment]
![image](https://cloud.githubusercontent.com/assets/22805853/19423786/633c0b1e-9456-11e6-9eee-79000e2d55ca.png)
心跳发送那个能行，我是不是在发送时必须启动一个什么文件？

**Comment by spacelan** [comment]
你是用的同一个wechat4u实例么？

**Comment by jiaojunjiaojun** [comment]
![image](https://cloud.githubusercontent.com/assets/22805853/19423915/8d3135ce-9457-11e6-8f0d-96cacb2cd24d.png)
我在example中的api中这样写行不

**Comment by spacelan** [comment]
先调用start()，login事件之后才能发送消息

**Comment by jiaojunjiaojun** [comment]
![image](https://cloud.githubusercontent.com/assets/22805853/19423962/04588508-9458-11e6-9400-9c75b1bacc94.png)
我是在这个文件中写的这个方法

**Comment by jiaojunjiaojun** [comment]
我在代码中这么调用启动，我对nodejs不熟，谢谢

**Comment by spacelan** [comment]
那你先写个登录API，监听uuid事件和login事件

**Comment by jiaojunjiaojun** [comment]
我能直接调用这个方法不

**Comment by spacelan** [comment]
start()和stop()都是同步返回的，其他消息通过监听事件来得到

或者你直接用core.js，然后参考wechat.js里的流程来写登录

**Comment by jiaojunjiaojun** [comment]
@spacelan 您好，我想把好友聊天的信息显示到页面上，不知道用什么方法显示到页面上

**Comment by spacelan** [comment]
@jiaojunjiaojun 你新开一个issue吧
