### ISSUE TITLE
web端编译报错

### ISSUE THREAD

**Issue by udbmnm** [nodeWechat/wechat4u#76]
ERROR in ./~/.0.4.0@wechat4u/lib/wechat.js                                      Module not found: Error: Can't resolve 'fs' in ‘\Chrome\node_modules\.0.4.0@wechat4u\lib'    

现在是不支持浏览器了吗?我切换到^0.2.5可以

**Comment by spacelan** [comment]
恩  稍等 我看一看

**Comment by spacelan** [comment]
```js
module.exports = {
  entry: './run-core.js',
  output: {
    path: './',
    filename: 'bundle.js',
  },
  module: {
    loaders: [{
      test: /\.json$/,
      loader: 'json'
    }]
  },
  node: {
    fs: 'empty',
    net: 'empty'
  }
}
```
试试这种配置？

**Comment by udbmnm** [comment]
@spacelan 直接require('wechat4u/lib/core') 可以，有些node模块没有会影响使用吗

**Comment by spacelan** [comment]
不影响的…在网页上用不到那些模块

**Comment by spacelan** [comment]
直接用最新版本吧不要用0.4.0了

**Comment by udbmnm** [comment]
@spacelan 好的，谢谢你

**Comment by spacelan** [comment]
你是在什么浏览器环境里跑的呢，我有点好奇😂

**Comment by udbmnm** [comment]
@spacelan 我在chrome extension里面，可惜不能直接使用wechat.js，只能仿照自己写了。。。

**Comment by udbmnm** [comment]
我刚试了可以直接使用wechat.js  :cold_sweat:

**Comment by spacelan** [comment]
我也是在chrome extension里面写了一个

另外run-core.js webpack以后也能在chrome extension里跑，不过会报读文件的不错，那文件操作删掉就好了

**Comment by udbmnm** [comment]
events.js?46b3:138(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

内存泄漏什么鬼。。。

**Comment by udbmnm** [comment]
@spacelan background打包出来2M+:sleepy:
