### ISSUE TITLE
我想把好友聊天的信息显示到页面上，不知道用什么方法显示到页面上好

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#77]

**Comment by spacelan** [comment]
我想到两个办法

1. WebSocket

2. 长连接

message事件得到的消息可以先放到一个消息队列中

**Comment by jiaojunjiaojun** [comment]
@spacelan 能否给个简单的例子

**Comment by stonexer** [comment]
及时显示到页面上么？

监听 message 事件 -> 给到前端页面 -> 显示出来...

**Comment by jiaojunjiaojun** [comment]
@spacelan 是的，谢谢

**Comment by jiaojunjiaojun** [comment]
@spacelan 你好用WebSocket这么实现，这个问题困扰我好长时间了，谢谢

**Comment by udbmnm** [comment]
@jiaojunjiaojun 这问题已经无法回答了，自己了解WebSocket协议
