### ISSUE TITLE
怎样将网络图片作为表情发送。

### ISSUE THREAD

**Issue by Flyphy** [nodeWechat/wechat4u#84]
bot.uploadMedia(fs.createReadStream('./media/test.png'))
      .then(res => {
        return bot.sendEmoticon(res.mediaId, msg.FromUserName)
      })
      .catch(err => {
        console.log(err)
      })

例如将 https://www.baidu.com/img/bd_logo1.png 上传至微信并发送此表情。

**Comment by Flyphy** [comment]
fs.createReadStream('./media/test.png')
改成
request('https://www.baidu.com/img/bd_logo1.png')提示图片上传失败

**Comment by spacelan** [comment]
因为request产生的stream拿不到size，然后微信api里size是必填的

所以必须先下载到本地来获取size。。。

**Comment by Flyphy** [comment]
get.

`request('https://www.baidu.com/img/bd_logo1.png').pipe(fs.createWriteStream('./media/aa.png'))
      bot.uploadMedia(fs.createReadStream('./media/aa.png'))
      .then(res => {
        return bot.sendEmoticon(res.mediaId, msg.FromUserName)
      })
      .catch(err => {
        console.log(err)
      })`

报以下错误

`----------15:45----------
zhaiwuji:	Test

又玩手机辣
  core { status: 200, statusText: 'OK', headers: { server: 'nginx', date: 'Wed, 02 Nov 2016 07:45:34 GMT', 'content-length': '125', connection: 'close', 'access-control-allow-origin': '*' }, config: { adapter: [Function: httpAdapter], transformRequest: { '0': [Function: transformRequest] }, transformResponse: { '0': [Function: transformResponse] }, headers: { Accept: 'application/json, text/plain, */*', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36', connection: 'close', cookie: 'pgv_pvi=475912192; pgv_si=s1254221824; webwx_data_ticket=gSey9tyLenqs24YIq1Fb4dP6; wxuin=196358974; wxsid=Y2zcsVyILAxONK02; wxloadtime=1478072672_expired; mm_lang=zh-CN; webwxuvid=a86bb6a5b873fdd6db550090476f0a09cb501c0f7c89acf00afe3cbf1b775aa7a38d7d8b97148313642f750189a1f37a; webwx_auth_ticket=CIsBEPztxQ0agAFUzwX2aKpWu6jgzHRUqHbmRYI/YwbWDIxxzTmNMlztzcKeprDi2Rlw8ubio8ZJf3zy+Yk4FJkxGF/0mJD5P778asPbsxeGAXCT8DzNc7oPfm0tHWe3cXjYGgpEZM0lP0/1mEXmIuNiIeSSR8zUTTz8UxK+qNOp/g/kig2YOuvhRA; wxpluginkey=1478047861', 'Content-Type': 'multipart/form-data; boundary=--------------------------751707586776033113569135' }, timeout: 0, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, validateStatus: [Function: validateStatus], httpAgent: false, httpsAgent: false, method: 'POST', url: 'https://file.wx2.qq.com/cgi-bin/mmwebwx-bin/webwxuploadmedia', params: { f: 'json' }, data: FormData { _overheadLength: 1127, _valueLength: 367, _lengthRetrievers: [Object], writable: false, readable: true, dataSize: 0, maxDataSize: 2097152, pauseStreams: true, _released: true, _streams: [], _currentStream: null, _boundary: '--------------------------751707586776033113569135', _events: {}, _eventsCount: 0 } }, request: ClientRequest { domain: null, _events: { error: [Object], prefinish: [Function: requestOnPrefinish] }, _eventsCount: 2, _maxListeners: undefined, output: [], outputEncodings: [], outputCallbacks: [], outputSize: 0, writable: true, _last: true, upgrading: false, chunkedEncoding: true, shouldKeepAlive: false, useChunkedEncodingByDefault: true, sendDate: false, _removedHeader: { connection: false }, _contentLength: null, _hasBody: true, _trailer: '', finished: true, _headerSent: true, socket: TLSSocket { _tlsOptions: [Object], _secureEstablished: true, _securePending: false, _newSessionPending: false, _controlReleased: true, _SNICallback: null, servername: null, npnProtocol: false, alpnProtocol: false, authorized: true, authorizationError: null, encrypted: true, _events: [Object], _eventsCount: 9, connecting: false, _hadError: false, _handle: null, _parent: null, _host: 'file.wx2.qq.com', _readableState: [Object], readable: false, domain: null, _maxListeners: undefined, _writableState: [Object], writable: false, allowHalfOpen: false, destroyed: true, _bytesDispatched: 2637, _sockname: null, _pendingData: null, _pendingEncoding: '', server: undefined, _server: null, ssl: null, _requestCert: true, _rejectUnauthorized: true, parser: null, _httpMessage: [Circular], read: [Function], _consuming: true, _idleNext: null, _idlePrev: null, _idleTimeout: -1 }, connection: TLSSocket { _tlsOptions: [Object], _secureEstablished: true, _securePending: false, _newSessionPending: false, _controlReleased: true, _SNICallback: null, servername: null, npnProtocol: false, alpnProtocol: false, authorized: true, authorizationError: null, encrypted: true, _events: [Object], _eventsCount: 9, connecting: false, _hadError: false, _handle: null, _parent: null, _host: 'file.wx2.qq.com', _readableState: [Object], readable: false, domain: null, _maxListeners: undefined, _writableState: [Object], writable: false, allowHalfOpen: false, destroyed: true, _bytesDispatched: 2637, _sockname: null, _pendingData: null, _pendingEncoding: '', server: undefined, _server: null, ssl: null, _requestCert: true, _rejectUnauthorized: true, parser: null, _httpMessage: [Circular], read: [Function], _consuming: true, _idleNext: null, _idlePrev: null, _idleTimeout: -1 }, _header: 'POST /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36\r\nconnection: close\r\ncookie: pgv_pvi=475912192; pgv_si=s1254221824; webwx_data_ticket=gSey9tyLenqs24YIq1Fb4dP6; wxuin=196358974; wxsid=Y2zcsVyILAxONK02; wxloadtime=1478072672_expired; mm_lang=zh-CN; webwxuvid=a86bb6a5b873fdd6db550090476f0a09cb501c0f7c89acf00afe3cbf1b775aa7a38d7d8b97148313642f750189a1f37a; webwx_auth_ticket=CIsBEPztxQ0agAFUzwX2aKpWu6jgzHRUqHbmRYI/YwbWDIxxzTmNMlztzcKeprDi2Rlw8ubio8ZJf3zy+Yk4FJkxGF/0mJD5P778asPbsxeGAXCT8DzNc7oPfm0tHWe3cXjYGgpEZM0lP0/1mEXmIuNiIeSSR8zUTTz8UxK+qNOp/g/kig2YOuvhRA; wxpluginkey=1478047861\r\nContent-Type: multipart/form-data; boundary=--------------------------751707586776033113569135\r\nHost: file.wx2.qq.com\r\nTransfer-Encoding: chunked\r\n\r\n', _headers: { accept: 'application/json, text/plain, */*', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36', connection: 'close', cookie: 'pgv_pvi=475912192; pgv_si=s1254221824; webwx_data_ticket=gSey9tyLenqs24YIq1Fb4dP6; wxuin=196358974; wxsid=Y2zcsVyILAxONK02; wxloadtime=1478072672_expired; mm_lang=zh-CN; webwxuvid=a86bb6a5b873fdd6db550090476f0a09cb501c0f7c89acf00afe3cbf1b775aa7a38d7d8b97148313642f750189a1f37a; webwx_auth_ticket=CIsBEPztxQ0agAFUzwX2aKpWu6jgzHRUqHbmRYI/YwbWDIxxzTmNMlztzcKeprDi2Rlw8ubio8ZJf3zy+Yk4FJkxGF/0mJD5P778asPbsxeGAXCT8DzNc7oPfm0tHWe3cXjYGgpEZM0lP0/1mEXmIuNiIeSSR8zUTTz8UxK+qNOp/g/kig2YOuvhRA; wxpluginkey=1478047861', 'content-type': 'multipart/form-data; boundary=--------------------------751707586776033113569135', host: 'file.wx2.qq.com' }, _headerNames: { accept: 'Accept', 'user-agent': 'user-agent', connection: 'connection', cookie: 'cookie', 'content-type': 'Content-Type', host: 'Host' }, _onPendingData: null, agent: Agent { domain: null, _events: [Object], _eventsCount: 1, _maxListeners: undefined, defaultPort: 443, protocol: 'https:', options: [Object], requests: {}, sockets: [Object], freeSockets: {}, keepAliveMsecs: 1000, keepAlive: false, maxSockets: Infinity, maxFreeSockets: 256, maxCachedSessions: 100, _sessionCache: [Object] }, socketPath: undefined, timeout: undefined, method: 'POST', path: '/cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json', _ended: true, parser: null, res: IncomingMessage { _readableState: [Object], readable: false, domain: null, _events: [Object], _eventsCount: 3, _maxListeners: undefined, socket: [Object], connection: [Object], httpVersionMajor: 1, httpVersionMinor: 1, httpVersion: '1.1', complete: true, headers: [Object], rawHeaders: [Object], trailers: {}, rawTrailers: [], upgrade: false, url: '', method: null, statusCode: 200, statusMessage: 'OK', client: [Object], _consuming: true, _dumped: false, req: [Circular], fetchedUrls: [Object], read: [Function] } }, data: { BaseResponse: { Ret: 1, ErrMsg: '' }, MediaId: '', StartPos: 0, CDNThumbImgHeight: 0, CDNThumbImgWidth: 0 } } +164ms
Error: 上传媒体文件失败
    at /Users/Flyphy/wechat4u/src/core.js:538:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
  wechat batchGetContact data length:  +16ms 1`

**Comment by spacelan** [comment]
`request('https://www.baidu.com/img/bd_logo1.png').pipe(fs.createWriteStream('./media/aa.png'))`
stream还没完成就开始上传了吧。。

**Comment by Flyphy** [comment]
如何判断 stream 完成再上传
