### ISSUE TITLE
bot.uploadMedia 接口每天有限额限制吗，测试一段时间后媒体上传失败了

### ISSUE THREAD

**Issue by Flyphy** [nodeWechat/wechat4u#85]
core { status: 200, statusText: 'OK', headers: { server: 'nginx', date: 'Thu, 03 Nov 2016 16:21:56 GMT', 'content-length': '309', connection: 'close', 'access-control-allow-origin': '*' }, config: { adapter: [Function: httpAdapter], transformRequest: { '0': [Function: transformRequest] }, transformResponse: { '0': [Function: transformResponse] }, headers: { Accept: 'application/json, text/plain, */*', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36', connection: 'close', cookie: 'pgv_pvi=1542490112; pgv_si=s1592886272; webwx_data_ticket=gSdlZSriZQ8t+H+YhSOFYl+2; wxuin=196358974; wxsid=CXPBwuyj7K6ZYT0p; wxloadtime=1478190086_expired; mm_lang=zh-CN; webwxuvid=a86bb6a5b873fdd6db550090476f0a092aac1e2a0b9b577859b8d975499112927ea5741957c02240ebdfc371d5d5a79a; webwx_auth_ticket=CIsBELrfzdIMGoABted3Tdrt2VQB/uwB1gigwUWCP2MG1gyMcc05jTJc7c22CZtqB5M/ZBIiXoI7DELgljWmJn/h8rk4+owaXw8MvEMFFwhEvDrsq2mMr2a5Hq7TKUeLlHoIZEEOFsroyCwktIrgkn92/mOz4NSWBiIialMSvqjTqf4P5IoNmDrr4UQ; wxpluginkey=1478167381', 'Content-Type': 'multipart/form-data; boundary=--------------------------858953728799556867126369' }, timeout: 0, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, validateStatus: [Function: validateStatus], httpAgent: false, httpsAgent: false, method: 'POST', url: 'https://file.wx2.qq.com/cgi-bin/mmwebwx-bin/webwxuploadmedia', params: { f: 'json' }, data: FormData { _overheadLength: 1127, _valueLength: 116885, _lengthRetrievers: [], writable: false, readable: true, dataSize: 0, maxDataSize: 2097152, pauseStreams: true, _released: true, _streams: [], _currentStream: null, _boundary: '--------------------------858953728799556867126369', _events: {}, _eventsCount: 0 } }, request: ClientRequest { domain: null, _events: { error: [Object], prefinish: [Function: requestOnPrefinish] }, _eventsCount: 2, _maxListeners: undefined, output: [], outputEncodings: [], outputCallbacks: [], outputSize: 0, writable: true, _last: true, upgrading: false, chunkedEncoding: true, shouldKeepAlive: false, useChunkedEncodingByDefault: true, sendDate: false, _removedHeader: { connection: false }, _contentLength: null, _hasBody: true, _trailer: '', finished: true, _headerSent: true, socket: TLSSocket { _tlsOptions: [Object], _secureEstablished: true, _securePending: false, _newSessionPending: false, _controlReleased: true, _SNICallback: null, servername: null, npnProtocol: false, alpnProtocol: false, authorized: true, authorizationError: null, encrypted: true, _events: [Object], _eventsCount: 9, connecting: false, _hadError: false, _handle: null, _parent: null, _host: 'file.wx2.qq.com', _readableState: [Object], readable: false, domain: null, _maxListeners: undefined, _writableState: [Object], writable: false, allowHalfOpen: false, destroyed: true, _bytesDispatched: 119174, _sockname: null, _pendingData: null, _pendingEncoding: '', server: undefined, _server: null, ssl: null, _requestCert: true, _rejectUnauthorized: true, parser: null, _httpMessage: [Circular], read: [Function], _consuming: true, _idleNext: null, _idlePrev: null, _idleTimeout: -1 }, connection: TLSSocket { _tlsOptions: [Object], _secureEstablished: true, _securePending: false, _newSessionPending: false, _controlReleased: true, _SNICallback: null, servername: null, npnProtocol: false, alpnProtocol: false, authorized: true, authorizationError: null, encrypted: true, _events: [Object], _eventsCount: 9, connecting: false, _hadError: false, _handle: null, _parent: null, _host: 'file.wx2.qq.com', _readableState: [Object], readable: false, domain: null, _maxListeners: undefined, _writableState: [Object], writable: false, allowHalfOpen: false, destroyed: true, _bytesDispatched: 119174, _sockname: null, _pendingData: null, _pendingEncoding: '', server: undefined, _server: null, ssl: null, _requestCert: true, _rejectUnauthorized: true, parser: null, _httpMessage: [Circular], read: [Function], _consuming: true, _idleNext: null, _idlePrev: null, _idleTimeout: -1 }, _header: 'POST /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36\r\nconnection: close\r\ncookie: pgv_pvi=1542490112; pgv_si=s1592886272; webwx_data_ticket=gSdlZSriZQ8t+H+YhSOFYl+2; wxuin=196358974; wxsid=CXPBwuyj7K6ZYT0p; wxloadtime=1478190086_expired; mm_lang=zh-CN; webwxuvid=a86bb6a5b873fdd6db550090476f0a092aac1e2a0b9b577859b8d975499112927ea5741957c02240ebdfc371d5d5a79a; webwx_auth_ticket=CIsBELrfzdIMGoABted3Tdrt2VQB/uwB1gigwUWCP2MG1gyMcc05jTJc7c22CZtqB5M/ZBIiXoI7DELgljWmJn/h8rk4+owaXw8MvEMFFwhEvDrsq2mMr2a5Hq7TKUeLlHoIZEEOFsroyCwktIrgkn92/mOz4NSWBiIialMSvqjTqf4P5IoNmDrr4UQ; wxpluginkey=1478167381\r\nContent-Type: multipart/form-data; boundary=--------------------------858953728799556867126369\r\nHost: file.wx2.qq.com\r\nTransfer-Encoding: chunked\r\n\r\n', _headers: { accept: 'application/json, text/plain, */*', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36', connection: 'close', cookie: 'pgv_pvi=1542490112; pgv_si=s1592886272; webwx_data_ticket=gSdlZSriZQ8t+H+YhSOFYl+2; wxuin=196358974; wxsid=CXPBwuyj7K6ZYT0p; wxloadtime=1478190086_expired; mm_lang=zh-CN; webwxuvid=a86bb6a5b873fdd6db550090476f0a092aac1e2a0b9b577859b8d975499112927ea5741957c02240ebdfc371d5d5a79a; webwx_auth_ticket=CIsBELrfzdIMGoABted3Tdrt2VQB/uwB1gigwUWCP2MG1gyMcc05jTJc7c22CZtqB5M/ZBIiXoI7DELgljWmJn/h8rk4+owaXw8MvEMFFwhEvDrsq2mMr2a5Hq7TKUeLlHoIZEEOFsroyCwktIrgkn92/mOz4NSWBiIialMSvqjTqf4P5IoNmDrr4UQ; wxpluginkey=1478167381', 'content-type': 'multipart/form-data; boundary=--------------------------858953728799556867126369', host: 'file.wx2.qq.com' }, _headerNames: { accept: 'Accept', 'user-agent': 'user-agent', connection: 'connection', cookie: 'cookie', 'content-type': 'Content-Type', host: 'Host' }, _onPendingData: null, agent: Agent { domain: null, _events: [Object], _eventsCount: 1, _maxListeners: undefined, defaultPort: 443, protocol: 'https:', options: [Object], requests: {}, sockets: [Object], freeSockets: {}, keepAliveMsecs: 1000, keepAlive: false, maxSockets: Infinity, maxFreeSockets: 256, maxCachedSessions: 100, _sessionCache: [Object] }, socketPath: undefined, timeout: undefined, method: 'POST', path: '/cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json', _ended: true, parser: null, res: IncomingMessage { _readableState: [Object], readable: false, domain: null, _events: [Object], _eventsCount: 3, _maxListeners: undefined, socket: [Object], connection: [Object], httpVersionMajor: 1, httpVersionMinor: 1, httpVersion: '1.1', complete: true, headers: [Object], rawHeaders: [Object], trailers: {}, rawTrailers: [], upgrade: false, url: '', method: null, statusCode: 200, statusMessage: 'OK', client: [Object], _consuming: true, _dumped: false, req: [Circular], fetchedUrls: [Object], read: [Function] } }, data: { BaseResponse: { Ret: 1205, ErrMsg: '' }, MediaId: '@crypt_710c07a2_9c10181e10d5059ca0c8c058d32a48e791e8d6d75247f8b28748e3a6593040a3ac5883c41a883c064dc3df3e2cf8b1eaaa48ff0da1b0d6a57e70fd97d25dbf9ba7bb0f880eb9299513e7407262b2414f', StartPos: 116499, CDNThumbImgHeight: 0, CDNThumbImgWidth: 0 } } +982ms
Error: 上传媒体文件失败

**Comment by spacelan** [comment]
```
 data: { BaseResponse: { Ret: 1205, ErrMsg: '' }, MediaId: '@crypt_710c07a2_9c10181e10d5059ca0c8c058d32a48e791e8d6d75247f8b28748e3a6593040a3ac5883c41a883c064dc3df3e2cf8b1eaaa48ff0da1b0d6a57e70fd97d25dbf9ba7bb0f880eb9299513e7407262b2414f', StartPos: 116499, CDNThumbImgHeight: 0, CDNThumbImgWidth: 0 }
```
wechat4u验证每一次请求的Ret，只要不是0就算请求失败

不过这里的MediaId其实是有值的，我试了，用这个MediaId还是能够成功发送图片。。

**Comment by spacelan** [comment]
我改了代码，你更新一下

**Comment by Flyphy** [comment]
经测试，Ret为1205时，返回的MediaId均指向一个图片（非上传的图片），应该是一段时间上传接口超过调用频率后会返回这样的数据。

**Comment by Flyphy** [comment]
赞，OK 了
