### ISSUE TITLE
有办法做到机器人邀请人加入群吗

### ISSUE THREAD

**Issue by vimer** [nodeWechat/wechat4u#87]

**Comment by spacelan** [comment]
网页版有这个API，大神有兴趣研究一下么？

**Comment by vimer** [comment]
@spacelan  老兄没时间研究了吗

**Comment by spacelan** [comment]
还是希望这个项目能有更多contributor

**Comment by vimer** [comment]
@spacelan  提供下微信，加个微信。

**Comment by spacelan** [comment]
spacelan

**Comment by wangzexi** [comment]
看起来仍然没有实现吗？

**Comment by spacelan** [comment]
@wangzexi 实现了

https://github.com/nodeWechat/wechat4u#botupdatechatroomchatroomusername-memberlist-fun

`bot.updateChatroom('@@roomusername', ['@contactusername'], 'addmember')`
