### ISSUE TITLE
如何发消息到群?

### ISSUE THREAD

**Issue by swuecho** [nodeWechat/wechat4u#89]
群usename 貌似是动态生成的

contacts里面又没有群信息

多谢

**Comment by spacelan** [comment]
https://github.com/nodeWechat/wechat4u/blob/master/src/interface/contact.js#L57

**Comment by swuecho** [comment]
多谢。



登录后，在手机上打开想要的群，然后bot.contacst 就会有该群的id 相关信息。


然后，找到群的地址。

  `let ToUserName  = Object.keys(bot.contacts).find( contact_id => bot.contacts[contact_id].OwnerUin=== 1561331240)
`

就可以发送信息到群了。

**Comment by spacelan** [comment]
恩 是的，网页版只能获取到部分最近联系的群信息
