### ISSUE TITLE
如何自动接受加群邀请？

### ISSUE THREAD

**Issue by bumfo** [nodeWechat/wechat4u#90]
现在人数多一点加群就需要确认了，如何用 wechat4u 自动确认呢？

**Comment by spacelan** [comment]
没有办法，网页版没有这个API

**Comment by bumfo** [comment]
刚才的加群邀请是您手动接受的嘛😂
话说微信怎么注册小号。。。买个新手机和手机号？

**Comment by bumfo** [comment]
观察发现 mac 版的微信是通过打开一个网页。。。说不定有对应的接口呢？

**Comment by spacelan** [comment]
我有一个测试机。。

**Comment by bumfo** [comment]
@spacelan 这样啊😂看来得试试研究客户端的接口了😂

**Comment by bumfo** [comment]
@spacelan 话说今天上线了更智能的机器人？🤖️

**Comment by spacelan** [comment]
临时接入，不稳定
