### ISSUE TITLE
不能多用户登录

### ISSUE THREAD

**Issue by jiaojunjiaojun** [nodeWechat/wechat4u#96]
部署到了服务器了，我登录操作后，另一个人后登录，我的状态就不存在了，相当于后一个人顶了我。

**Comment by udbmnm** [comment]
@jiaojunjiaojun 是的，菊花一顶，前一个就爆了

**Comment by stonexer** [comment]
是跑的 example 里的么，可以看下 log 里的数据么

**Comment by jiaojunjiaojun** [comment]
是的

**Comment by jiaojunjiaojun** [comment]
![image](https://cloud.githubusercontent.com/assets/22805853/20780016/41b0e192-b7b3-11e6-8332-f9b89f40a8d1.png)

**Comment by jiaojunjiaojun** [comment]
这是用2个微信号扫描登录的数据

**Comment by spacelan** [comment]
这个web服务器是为了展示wechat4u的功能而开发的，有些不完善，使用时需要小心一点

**Comment by jiaojunjiaojun** [comment]
@stonexer 你好，我用2个微信号扫描登录，然后好友发过来的信息我这么区分是发给那个微信号的，

**Comment by spacelan** [comment]
每个微信号都是一个单独的`Wechat`实例

你直接判断那个实例的`user`对象就好了

**Comment by jiaojunjiaojun** [comment]
已解决，谢谢@spacelan
